### ISSUE TITLE
Ability to add arbitrary metadata to Report Entries

### ISSUE THREAD

**Issue by austince** [onsi/ginkgo#1011]
While building on top of the programmatic reporting infrastructure, I've had some situations where I want to add different types of report entries throughout the tests and collect a portion of those afterwards to build a custom report from. Currently, only `Offset`, `CodeLocation`, and `time.Time` args are allowed for customizing the entry: https://onsi.github.io/ginkgo/#attaching-data-to-reports

I'm wondering what the best approach would be here. My first thoughts are to add support for Labels to ReportEntries, which could be attached when they're created, e.g.

```go
AddReportEntry("important debug statement", "bar", Label("debug"))
AddReportEntry("general report entry", "foo"))


// And then
AfterEach(func() {
  reportEntries := CurrentSpecReport().ReportEntries
  matches, _ := reportEntries.MatchesLabelFilter("debug")
  // do something with the matching entries
})
```

Wdyt? Does this use case make sense / is it covered elsewhere?

**Comment by onsi** [comment]
hey @austince - you can attach anything you want to the `ReportEntry` - for this usecase I'd suggest defining your own type and attaching instances of it.  You can also craft your own DSL while you're at it:

```go
type DebugStatement struct {
    Short string
    Details string
}

func DS(short string, details ...string) DebugStatement {
    out := DebugStatement{Short: short}
    if len(details) > 0 {
        out.Details = details[0]
    }
    return out
}

// then
AddReportEntry("important debug statement", DS("bar", "wobble"))
```

It's not far from there to having a helper function that can identify `DebugStatement` entries and pull them out for you in the `AfterEach`.  And you can get into [formatting Ginkgo's default output](https://onsi.github.io/ginkgo/#controlling-output) for `DebugStatement` .  Note that there are a [few details you'll need to attend to](https://github.com/onsi/ginkgo/blob/master/types/report_entry.go#L115-L122) if you are running in parallel.  I'd be happy to put together a more fleshed out example if that would be helpful.

---

### Why not just add `Label` to `AddReportEntry`?

My main reason is because `Label` has a specific semantic meaning around labeling and filtering _specs_.   I can see people conditionally adding `AddReportEntry` `Label`s and then wondering why Ginkgo isn't filtering those specs out correctly when using the `--label-filter` flag.  Given `AddReportEntry` supports attaching _anything_ I figure the building blocks are there for folks to build on top of?

**Comment by austince** [comment]
Hey, that makes a lot of sense to me, especially regarding the `--label-filter` flag. The ability to add anything does provide a nice workaround here, I guess the downsides are that the logic that handles the values needs to be updated or include support for whatever wrapper types are used. This doesn't seem like a big enough issue to do anything about right now, so thanks again for the thoughtful answer!
