### ISSUE TITLE
Output verbosity, context outputs should be grouped

### ISSUE THREAD

**Issue by eriknyk** [onsi/ginkgo#1031]
by example:

<img width="553" alt="Screen Shot 2022-08-31 at 16 50 34" src="https://user-images.githubusercontent.com/205721/187792009-f35f60e9-b9c3-43e9-9cec-063624cad201.png">

If we have:

```
var _ = Describe("Users", func() {
	Describe("Get All", Ordered, func() {
		res := HttpGet(server.App(), "/users")
                 // ...
		Context("when no users registered", Ordered, func() {
			It("returns status 200", func() {
				Expect(res.StatusCode).To(Equal(http.StatusOK))
			})
			It("returns an empty array", func() {
				Expect(len(result)).To(Equal(0))
				Expect(result).To(Equal(expected))
			})
		})
	})
```

Currently we have:
```
Will run 2 of 2 specs
------------------------------
Users Get all when no users registered
  returns status 200
  /Users/erik/Projects2/posman-core/tests/suite/users_test.go:56
•
------------------------------
Users Get all when no users registered
  returns an empty array
  /Users/erik/Projects/.../tests/suite/users_test.go:59
•

Ran 2 of 2 Specs in 0.001 seconds
```

But looks like the context outputs should be grouped, like the following output:
```
Will run 2 of 2 specs
------------------------------
Users Get All when no users registered
  returns status 200
  returns an empty array
  /Users/erik/Projects/.../tests/suite/users_test.go:56
••
Ran 2 of 2 Specs in 0.001 seconds

```

Best Regards.

**Comment by onsi** [comment]
hey @eriknyk - since Ginkgo supports spec [parallelization](https://onsi.github.io/ginkgo/#spec-parallelization) and [randomization](https://onsi.github.io/ginkgo/#spec-randomization) there are no guarantees that specs will run in context-order.  Moreover, Ginkgo assumes [specs are independant](https://onsi.github.io/ginkgo/#mental-model-ginkgo-assumes-specs-are-independent).

So, while I do appreciate that the approach you're advocating for would be less verbose... in practice it would not always workout that specs within a given context run together.

FWIW you should only see this output if you are running `ginkgo -v` - in which case you are opting into verbosity.  Ginkgo's default behavior is to just show green dots and only emit all that location information on failure.

**Comment by eriknyk** [comment]
Thanks for the sooner response @onsi, and I'm agree with that
however I most of our test cases we're using  [Ordered Containers](https://onsi.github.io/ginkgo/#ordered-containers)
because for us, is important test with the accordance of an order of events.

In this case that proposed above would make sense?

**Comment by onsi** [comment]
hey there, sorry for the delay.  Understood - in general while Ordered Containers exist and are fully supported my preference is to nudge users towards using smaller independent `It's where possible... and to avoid adding additional complexity and "special" behavior to Ordered Containers.  Part of this is because of growing complexity in the Ginkgo codebase to support Ordered Containers - but part of it is also due to growing complexity in the mental model of how Ginkgo specs are written, organized and run.

All this to say: while the feature request makes sense - it's not something I'll be  prioritizing in the short term.
