### ISSUE TITLE
Detect that the BeforeSuite failed for any reason before DeferCleanup kicks in

### ISSUE THREAD

**Issue by thof** [onsi/ginkgo#1045]
My issue is very similar to this one https://github.com/onsi/ginkgo/issues/873 but it didn't cover my use case since I want to detect a failure that occurs in the `BeforeSuite` and capture the debug logs before the `DeferCleanup` kicks in. For example:
```
var _ = BeforeSuite(func() {
	// deploy some stuff to Kubernetes
        // set DeferCleanup to delete created objects afterwards
})

// some specs with tests
...

var _ = AfterSuite(func() {
        // here I want to detect somehow that the BeforeSuite failed
})

// it's too late to collect logs as the deployments are in deleting phase at this point
var _ = ReportAfterSuite("Report after failure", func(report Report) {
	beforeSuite := report.SpecReports.WithLeafNodeType(types.NodeTypeBeforeSuite)
	if beforeSuite[0].Failed() {
		// collect logs
	}
})

```
Any ideas how to achieve it? @onsi

**Comment by onsi** [comment]
hey there @thof - here are a couple of options:

### Catch the Failure with a `defer`

You can do something like this:

```go
var _ = BeforeSuite(func() {
	defer func() {
		if r := recover(); r != nil {
			// collect logs
			panic(r)
		}
	}()
	// deploy some stuff to Kubernetes
        // set DeferCleanup to delete created objects afterwards
})
```

This works because Ginkgo throws a panic when `Fail` is called (either directly, or via a failed Gomega assertion).  Note that you need to rethrow the panic with `panic(r)` to make sure Ginkgo detects the failure.

### Track the Failure State Manually

You can do also do something like this:

```go
var beforeSuitePassed = false

var _ = BeforeSuite(func() {
	// deploy some stuff to Kubernetes
        // set DeferCleanup to delete created objects afterwards
        beforeSuitePassed = true // make this the last line of code in your BeforeSuite
})

var _ = AfterSuite(func() {
    if !beforeSuitePassed {
        // collect logs
    }
})
```
This works, again, because Ginkgo throws a panic when `Fail` is called and so you'll only get to the `beforeSuitePassed=true` line if the `BeforeSuite` succeeds.

### If possible, just always collect the logs

This might not work for your setup but I usually just have anything that generates logs pipe them into `GinkgoWriter`.  Then, if a failure occurs, I know that Ginkgo will display all the relevant information.  My guess is that in your case you have to actually make a network request to get at the logs and so you're really more in a situation where a failure needs to cause an explicit event to occur... so this won't work for you?

If it's relatively cheap to collect the logs, though, you _can_ do something like:

```go
var logs string
var _ = AfterSuite(func() {
       logs = // collect logs, always.
})

// it's too late to collect logs as the deployments are in deleting phase at this point
var _ = ReportAfterSuite("Report after failure", func(report Report) {
	beforeSuite := report.SpecReports.WithLeafNodeType(types.NodeTypeBeforeSuite)
	if beforeSuite[0].Failed() {
		// print logs
	}
})
```

**Comment by thof** [comment]
Great, many thanks for these suggestions! 

Collecting all logs can be a bit expensive so I think I will go with the second options since it the easiest one and will just work.

But there is another thing that surprised me, i.e. I thought I'll be able to use the GinkgoWriter to print these logs after BeforeSuite failure but it didn't work. I noticed in docs that it's only triggered after a spec failure. So it seems that in case of `if !beforeSuitePassed` I should write directly to stdout, right?

**Comment by onsi** [comment]
Ah yes, that's right.  Only the GinkgoWriter output associated with a failed spec is displayed and the BeforeSuite is modeled as a distinct spec.

I think option 1 might be cleanest from a lifecycle perspective as you are basically staying within the BeforeSuite's lifecycle.

Otherwise you _can_ print to stdout for AfterSuite and that will work even when running in parallel (because Ginkgo captures all stdout/stderr output).  However you could also use [AddReportEntry](https://onsi.github.io/ginkgo/#attaching-data-to-reports) to attach the logs to the AfterSuite report *or* you could write to GinkgoWriter and then call Fail in the AfterSuite to have it emit the GinkgoWriter output.

Of these I'd recommend AddReportEntry as it's a bit more structure than simply logging to the console.

**Comment by thof** [comment]
Cool, so I ended up with the the 1st option as you suggested and writing logs to stdout after BeforeSuite failed and it works very well so far. Thanks again for these great ideas!
