### ISSUE TITLE
v2.3.0: flag provided but not defined: -ginkgo.grace-period

### ISSUE THREAD

**Issue by JoelSpeed** [onsi/ginkgo#1055]
I installed the new ginkgo cli today with `go install github.com/onsi/ginkgo/v2/ginkgo@v2.3.0`

When I run `ginkgo -r`, I get an error `flag provided but not defined: -ginkgo.grace-period`, even though I haven't specced that flag.
If I downgrade to v2.2.0 (`go install github.com/onsi/ginkgo/v2/ginkgo@v2.2.0`) then I can run the same command and it works as expected.

I notice between the v2.2.0 and v2.3.0 releases there have been changes which introduced a new grace period option ([commit](https://github.com/onsi/ginkgo/commit/16f56acdebb6c1567a945201e67973b62cdfbae2)) for the test contexts, so I suspect the PR that introduced that has cause this issue, though from my scanning of the code I can't quite see how.

Is there something automatically generating flags or something?

Anyway, I suspect @onsi might have a better idea.

**Comment by onsi** [comment]
hey @JoelSpeed take a look at #1050 - the version of the cli and the version of ginkgo in your `go.mod` have to match.  2.3.0 added a new flag that the cli is sending to the compiled test binary - but v2.2.0 of the library doesn't define that flag and `go test`'s behavior is to bail because of the undefined flag.

 you can upgrade your go.mod to the latest or stay on v2.2.0.  either way you should build the version of the cli that matches your `go.mod` by running `go install github.com/onsi/ginkgo/v2/ginkgo` from within your package.

**Comment by JoelSpeed** [comment]
Ack, thanks for the quick response, that's not particularly intuitive but I can see from the other thread why this happens.

I wonder if there's a way to improve the output with some warning that this is a thing.

It does make it very hard to install the CLI on my laptop for IDE Integration, but perhaps I can come up with a way to solve that separately, we can close this and continue the discussion in the other thread

**Comment by onsi** [comment]
tell me about It! :/ go test's default behavior around these flag issues is not super great or easy to hook into/tweak.

one thing that might work is to always use `go run github.com/onsi/ginkgo/v2/ginkgo` instead of `ginkgo` - but you'll need to tell your side to run from within the working directory in question so the go toolchain can see the correct go.mod (and, I think, `go run` won't recompile ginkgo every time... but it might? I'm not sure)

**Comment by JoelSpeed** [comment]
Yeah a go run based solution is what I was thinking, I use that in a lot of makefiles already but haven't tried it for the IDE Integration yet

Go run does recompile every time AFAIK which is both good and bad!
