### ISSUE TITLE
output: record all events related to a test in GinkgoWriter

### ISSUE THREAD

**Issue by pohly** [onsi/ginkgo#1069]
When debugging a test failure in Kubernetes, the steps to investigate are usually:
- look at failure message
- look at stderr for the test (= output captured via GinkgoWriter)
- look at the full job output (last resort, because it can be large)

For the second step, we log test failures as they occur in the GinkgoWriter. This works for gomega because it calls our custom fail handler, which then calls ginkgo.Fail. It does not work for timeouts or other failures detected by ginkgo itself, like an error that is returned to DeferCleanup.

**Comment by onsi** [comment]
I hope to work on this within the next couple of weeks.  Rather than flatten everything into the `GinkgoWriter` stream I'm going to introduce the notion of a timeline of events that incorporate all the things that happen during a spec.  This timeline can be constructed from the `SpecReport`.

I'm going to then explore different ways of formatting and presenting that timeline and, in doing so, _might_ finally manage to clean up some of Ginkgo's growing sprawl of reporting configuration flags.

One thing I'm happy to commit to is to update the JUnit reporter so that the content of `stderr` is the full timeline.

**Comment by pohly** [comment]
Skipping is another event where Kubernetes currently has a custom wrapper to log the event as it occurs.

**Comment by onsi** [comment]
Yes, thanks - I'll make sure that gets included in the timeline.

**Comment by onsi** [comment]
hey @pohly I have a working version of this on the [timeline](https://github.com/onsi/ginkgo/tree/timeline) branch.  I haven't redone Ginkgo's unit and integration tests yet (that will take some time as some plumbing and behavior has changed) but I wanted to get this out for some feedback sooner rather than later.

You shouldn't have to change any of your code.  The `--progress`, `--slow-spec-threshold`, and `--always-emit-ginkgo-writer` are now meaningless and will be formally deprecated (i.e. they will emit a deprecation warning if provided) when I ship this code.  They just aren't necessary any more.

The new behavior is as follows:

Rather than present spec-related events in different sections, Ginkgo now tries to combine everything into a single stream and tacks the primary failure (i.e. the first failure to occur) on at the end to make it easier for users to see what failed-at-a-glance.  The stream includes all the items listed above and is called the spec's "timeline".

when running `ginkgo` the timeline is only emitted for failed specs.  When running `ginkgo -v` or `ginkgo -vv` the timeline is emitted in real-time.  When running in parallel with `ginkgo -v -p` or `ginkgo -vv -p` the timeline is emitted when the spec completes

`-v` and `-vv` now better encapsulate two levels of verbosity:

With `-v`, or when a failure occurs, the timeline will include:

- data written to GinkgoWriter
- calls to By
- repetitions due to FlakeAttempts and MustPassRepeatedly
- ReportEntries being added
- ProgressReports being generated
- simple annotations when a failure or timeout occurs

The full-fledge failure does not appear in the timeline; only in a section at the end.  However a [FAILED] tag is injected into the timeline.  This  way users know to always look at the bottom to see the failure, but then can cross-reference where it occurs by looking at their console output.

With `-vv` the timeline also includes:
- nodes start/finish running
-  for By's with callbacks: when the By finishes
- full-fledged error failure reports in the timeline (not just a [FAILED] tag).

With `-vv` there is no failure summary at the end.  Everything appears in the timeline

The JUnit reporter does the following:
- Every spec (regardless of status) always includes the full `-vv` version of the timeline in `system-err`.
- In addition, failed specs get a summary of the primary failure in body of the `Failure` tag.  The "message " attribute of the `Failure` tag only includes the failure message as before.

There is one subtlety here.  In the event that a node timesout and then a failure is recorded after the timeout them the "message" attribute will only say "A node timeout occurred" and you will need to look at the body of the `Failure` tag to get the timeout and the follow-on failure.  This will happen in cases such as:

```go
Eventually(ctx, foo).Should(Equal(bar))
```

the expiration of `ctx` is the timeout failure that is reported and shortly after the timeout occurs `Eventually` will fail with a message that says `Expected foo to equal bar`.  This secondary failure only appears in the body of the tag and not the message itself.

**Comment by pohly** [comment]
This sounds good. Some comments on a few things:

> `--progress` is now meaningless

I see one small usability regression here: right now, I can use `ginkgo --progress --poll-progress-after=1m  -v --nodes=15` and I will get notified after 1 minute about tests that are still running. It sounds like in the future I will have to wait for the test to complete, fail or timeout before it's timeline is shown, right?

It doesn't matter for a CI system, but for interactive usage polling and intermediate progress reports are useful.

> With -vv the timeline also includes:

This is probably what we'll use in Kubernetes.

> In addition, failed specs get a summary of the primary failure in body of the Failure tag. The "message " attribute of the Failure tag only includes the failure message as before.

This part is not clear to me. What is the difference between "failure message" and "summary of the primary failure"? An example would be useful.

In https://github.com/kubernetes/test-infra/pull/27831 I am proposing to combine failure message tag and content to restore what the tool was previously working with (message + backtrace). If we do that, will we start to get duplicated text with the timeline branch?

**Comment by onsi** [comment]
> It sounds like in the future I will have to wait for the test to complete, fail or timeout before it's timeline is shown, right?

No, actually.  Sorry for the confusion.  The only thing `--progress` was doing was emitting to the `GinkgoWriter` when Ginkgo starts running a node.  These are now always included in the timeline - but they are only shown when rendering with `-vv`.  Since the JUnit report effectively renders with `-vv` it will include these annotations.

Going forward you are correct that events will only appear in the timeline portion of the spec report on the console when running in parallel.  However there is one exception, precisely for the use-case you describe: any `ProgressReports` generated by the built-in polling (`--poll-progress-after`/`PollProgressAfter()`) or requested by the user (`SIGINFO`/`SIGUSR1`) will always be immediately emitted to the console.  They will _also_ appear in the timeline of the spec report when it eventually prints out (so this is one of the few things that is still duplicated).

---

> This (`-vv`) is probably what we'll use in Kubernetes

You can.  But you actually don't need to.  You can just run `ginkgo` without `-vv` or even `-v`.  That will help keep your console logs smaller and easier to read (and you'll still get timelines for failed specs).  Since the JUnit reports always render with `-vv` you have all the details stored there.

This is one of the reasons I took the approach I did.  Rather than move closer to coupling spec information to `GinkgoWriter` output which collapses data and presentation I've moved in the opposite direction.  All these various events are now just data attached to the report and Ginkgo can render it in different ways depending on the context.

---

> This part is not clear to me. What is the difference between "failure message" and "summary of the primary failure"? An example would be useful

Sorry for not being clear.  Let me lay it out more verbosely.

Let's say you have:

```go
It("fails", func(ctx SpecContext) {
    GinkgoWriter.Println("let's wait a bit")
    <-ctx.Done()
    GinkgoWriter.Println("looks like we timed out")
    Fail("boom")
}, NodeTimeout(time.Second))

AfterEach(func() {
    Fail("again")
})
```

There are three distinct failure events here:
1. The timeout failure that triggers while `<-ctx.Done()` is waiting.  The message for this failure is generated by Ginkgo and reads `"A node timeout occurred"`
2. The subsequent failure that occurs in the `It` after the timeout is triggered.  The message for this failure is
   ```
   "A node timeout occurred and then the following failure was recorded in the timedout node before it exited:
   boom"
   ```
3. The additional failure that occurs in the `AfterEach`.  The message here is simply `"again"`

when the test ends the following is emitted to the console:

```
• [TIMEDOUT] [1.004 seconds]
A sample suite
/Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:20
  example
  /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:21
    [It] fails
    /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22

  Timeline >>
  let's wait a bit
  [TIMEDOUT] in [It] - /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22 @ 11/01/22 13:17:54.896
  looks like we timed out
  [FAILED] in [It] - /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:26 @ 11/01/22 13:17:54.898
  [FAILED] in [AfterEach] - /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:30 @ 11/01/22 13:17:54.899
  << Timeline

  [TIMEDOUT]
  A node timeout occurred
  In [It] at: /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22

  This is the Progress Report generated when the node timeout occurred:
    A sample suite example fails (Spec Runtime: 1.002s)
      /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22
      In [It] (Node Runtime: 1.002s)
        /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22

      Spec Goroutine
      goroutine 6 [chan receive]
      > github.com/onsi/ginkgo/v2/reporters/sample_test.glob..func1.1.1({0x102606290, 0x14000139940})
          /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:24
            | It("fails", func(ctx SpecContext) {
            |   GinkgoWriter.Println("let's wait a bit")
            >   <-ctx.Done()
            |   GinkgoWriter.Println("looks like we timed out")
            |   Fail("boom")
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
          /Users/onsi/code/ginkgo/internal/suite.go:822
        github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
          /Users/onsi/code/ginkgo/internal/suite.go:809

  [FAILED]
  A node timeout occurred and then the following failure was recorded in the timedout node before it exited:
  boom
  In [It] at: /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:26

  There were additional failures detected after the initial failure.  To view them in detail run ginkgo -vv
```

A few things to call out:

- The timeline shows exactly where the timeout occurs and the subsequent failures.  Note that intermediate GinkgoWriter lines are included as well.
- Just a single-line summary of each failure is included in the timeline
- The full-blown failure message appears after the timeline.  And by default Ginkgo only shows the failure message for the **primary** failure. This is the **first** failure that occurs (i.e. the Timeout).  As you can seee the full message includes:
    - the type of failure
    - the failure message
    - the location of the failure
    - any progress reports associated with the failure.
- There is a special case where Ginkgo associates a single additional failure with the primary failure.  If a node is interrupted or times out, and then an additional failure occurs before the node exits, Ginkgo will attach that failure to the timeout/interrupt failure.  In this case you see the full-blown failure message for the `boom` failure.
- By default any additional follow-on failures are not included in full.  They are just noted in the timeline.  Hence we don't see the `again` failure.

The Junit file for this test looks like this:

```
<testcase name="[It] A sample suite example fails" classname="Sample Suite" status="timedout" time="1.003476792">
  <failure message="A node timeout occurred" type="timedout">
      [TIMEDOUT]
      A node timeout occurred
      In [It] at: /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22

      This is the Progress Report generated when the node timeout occurred:
        A sample suite example fails (Spec Runtime: 1.001s)
          /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22
          In [It] (Node Runtime: 1.001s)
            /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22

          Spec Goroutine
          goroutine 23 [chan receive]
          > github.com/onsi/ginkgo/v2/reporters/sample_test.glob..func1.1.1({0x102a22290, 0x1400009a2c0})
              /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:24
                | It("fails", func(ctx SpecContext) {
                |   GinkgoWriter.Println("let's wait a bit")
                >   <-ctx.Done()
                |   GinkgoWriter.Println("looks like we timed out")
                |   Fail("boom")
            github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
              /Users/onsi/code/ginkgo/internal/suite.go:822
            github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
              /Users/onsi/code/ginkgo/internal/suite.go:809

      [FAILED]
      A node timeout occurred and then the following failure was recorded in the timedout node before it exited:
      boom
      In [It] at: /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:26

      There were additional failures detected after the initial failure. These are visible in the timeline
  </failure>

  <system-err>
      > Enter [It] fails - /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22 @ 11/01/22 13:26:30.884
      let's wait a bit
      [TIMEDOUT]
      A node timeout occurred
      In [It] at: /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22

      This is the Progress Report generated when the node timeout occurred:
        A sample suite example fails (Spec Runtime: 1.001s)
          /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22
          In [It] (Node Runtime: 1.001s)
            /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22

          Spec Goroutine
          goroutine 23 [chan receive]
          > github.com/onsi/ginkgo/v2/reporters/sample_test.glob..func1.1.1({0x102a22290, 0x1400009a2c0})
              /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:24
                | It("fails", func(ctx SpecContext) {
                |   GinkgoWriter.Println("let's wait a bit")
                >   <-ctx.Done()
                |   GinkgoWriter.Println("looks like we timed out")
                |   Fail("boom")
            github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
              /Users/onsi/code/ginkgo/internal/suite.go:822
            github.com/onsi/ginkgo/v2/internal.(*Suite).runNode
              /Users/onsi/code/ginkgo/internal/suite.go:809

              [FAILED]
      A node timeout occurred and then the following failure was recorded in the timedout node before it exited:
      boom
      In [It] at: /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:26
      looks like we timed out
      [FAILED]
      A node timeout occurred and then the following failure was recorded in the timedout node before it exited:
      boom
      In [It] at: /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:26
      < Exit [It] fails - /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:22 @ 11/01/22 13:26:31.887 (1.003s)
      > Enter [AfterEach] example - /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:29 @ 11/01/22 13:26:31.887
      [FAILED]
      again
      In [AfterEach] at: /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:30
      < Exit [AfterEach] example - /Users/onsi/code/ginkgo/reporters/sample/sample_suite_test.go:29 @ 11/01/22 13:26:31.888 (0s)
  </system-err>
</testcase>
```

The failure `message` only includes the message of component of the primary failure.  However the description includes the full failure (and any associated additional failure int he case of an interrupt or timeout).

Note that the timeline in `system-err` is rendered as with `-vv` and so it includes the `> Enter [It]` and `< Exit [It]` node events and it includes every failure that occurs in full form (e.g. you can see the `again` failure at the bottom).

Going forward I think you just need to grab the body part of the `failure` tag and not bother with `message`.  The body will include all the details about where the failure occurred and any progress reports associated with it.

**Comment by pohly** [comment]
Thanks for the details, this does indeed look very promising.

> Going forward I think you just need to grab the body part of the failure tag and not bother with message. The body will include all the details about where the failure occurred and any progress reports associated with it.

Agreed, for Ginkgo. The problem just is that our tools need to process JUnit from various sources and cannot make assumptions about which parts of the failure are relevant. To be on the safe side, we either have to concatenate unconditionally (done by all tools right now since my PR for kettle was merged yesterday) or add another heuristic: if the failure's message tag is contained in the failure's data, then we can drop the message.

We don't even need to do that in the tools. Instead, we can do that in our post-processing of the JUnit output for those tools in the E2E framework.

**Comment by pohly** [comment]
I've tried this out in https://github.com/kubernetes/kubernetes/pull/113538. Some observations.

In https://github.com/kubernetes/kubernetes/blob/07315d10b3718973e5ebcc61cbf0fba8a6ec58a9/test/e2e/framework/test_context.go#L529-L573, we write a simpler JUnit report where only failed specs have `system-err` and most specs don't have `system-out` because we remove the "By Step" report entries that normally land there. With the timeline changes, I see that `system-err` is always filled with the timeline. @onsi : can you perhaps add a SpecReport.SkipTimeline boolean, false by default, which our code can set to true to prevent writing the timeline?

In https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113538/pull-kubernetes-e2e-gce-ubuntu-containerd/1587812643610038272 I only get shown this as failure by spyglass:
```
{ failed [FAILED]
In [It] at: test/e2e/node/pods.go:474
}
```

I think the curly brackets are a bug in spyglass - let's ignore that for now. But the failure message from [test/e2e/node/pods.go:474](https://github.com/kubernetes/kubernetes/blob/07315d10b3718973e5ebcc61cbf0fba8a6ec58a9/test/e2e/node/pods.go#L474) is not there either.

The [full JUnit report for one failure](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/113538/pull-kubernetes-e2e-gce-ubuntu-containerd/1587812643610038272/artifacts/ginkgo_report.xml) is
```
<failure message="1 errors: pod pod-terminate-status-1-8 on node e2e-eac170df43-a7d53-minion-group-7sg3 container unexpected exit code 128: start=1970-01-01 00:00:00 +0000 UTC end=2022-11-02 15:08:47 +0000 UTC reason=StartError message=failed to create containerd task: failed to start shim: start failed: : signal: killed: unknown" type="failed">
[FAILED] 1 errors: pod pod-terminate-status-1-8 on node e2e-eac170df43-a7d53-minion-group-7sg3 container unexpected exit code 128: start=1970-01-01 00:00:00 +0000 UTC end=2022-11-02 15:08:47 +0000 UTC reason=StartError message=failed to create containerd task: failed to start shim: start failed: : signal: killed: unknown In [It] at: test/e2e/node/pods.go:474
</failure>
```

The [pruned one](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/113538/pull-kubernetes-e2e-gce-ubuntu-containerd/1587812643610038272/artifacts/junit_01.xml):
```
<failure message="" type="failed">[FAILED] In [It] at: test/e2e/node/pods.go:474 </failure>
```

That explains it: setting `specReport.Failure.Message` to "" removed the information from both fields. My cunning plan backfired...

Could the JUnit report writer perhaps get a new flag for "don't write message tag"?

**Comment by onsi** [comment]
hey @pohly I think the approach I'd want to take is to make a `JunitReportConfig` struct like:

```
type JunitReportConfig {
   OmitTimelinesFor types.SpecState
   OmitFailureMessageTag bool
   OmitCapturedStdOutErr boo,
}
```

and add a new

```
reporters.GenerateConfiguredJUnitReport(report, jUnitReport, config)
```

I think you could then replace all of `writeJUnitReport` with:

```go
writeJUnitReport(report ginkgo.Report) {
	junitReport := path.Join(TestContext.ReportDir, "junit_"+TestContext.ReportPrefix+"01.xml")
	reporters.GenerateConfiguredJUnitReport(trimmedReport, junitReport, reporters.JUnitReporterConfig{
              SkipTimelinesFor: types.SpecStatePassed | types.SpecStateSkipped | types.SpecStatePending,
              OmitFailureMessageTag: true,
              OmitCapturedStdOutErr: true,
        })
}
```

Note: you no longer need to trim `ReportEntries` as `By` no longer generates a `ReportEntry`; and you no longer need to clear out `CapturedGinkgoWriterOutput`.  Also,I don't think you need `specReport.CapturedStdOutErr = ""`  _or_ the `OmitCapturedStdOutErr` I'm proposing since nothing on Ginkgo's side should be printing to stdout/err.  But I'm happy to include it anyway.

**Comment by pohly** [comment]
That proposal looks good. I can leave OmitCapturedStdOutErr unset just in case that something shows up there (although it shouldn't).

**Comment by onsi** [comment]
👍 should get it done today on the timeline branch

**Comment by onsi** [comment]
This is on the latest timeline branch now with:

```go
type JunitReportConfig struct {
	// Spec States for which no timeline should be emitted for system-err
	// set this to types.SpecStatePassed|types.SpecStateSkipped|types.SpecStatePending to only match failing specs
	OmitTimelinesForSpecState types.SpecState

	// Enable OmitFailureMessageAttr to prevent failure messages appearing in the "message" attribute of the Failure and Error tags
	OmitFailureMessageAttr bool

	//Enable OmitCapturedStdOutErr to prevent captured stdout/stderr appearing in system-out
	OmitCapturedStdOutErr bool
}

GenerateJUnitReportWithConfig(report types.Report, dst string, config JunitReportConfig)
```

**Comment by pohly** [comment]
Writing the reports worked as intended, at least for a job where nothing failed. Unfortunately there was none of the usual tests flakes :grin: 

For such a run, I get the following reports:
```
ginkgo_report.json 36622382
ginkgo_report.xml  21378427
junit_01.xml        2344662
```

The last one is the truncated one, the others are the normal Ginkgo reports.

**Comment by onsi** [comment]
🙌 excellent 😊

**Comment by pohly** [comment]
I added some intentional failures. Spyglass reports them as:
```
Kubernetes  e2e suite: [It] [sig-storage] In-tree Volumes [Driver: hostPath]  [Testpattern: Inline-volume (default fs)] subPath should be able to  unmount after the subpath directory is deleted [LinuxOnly] 
{ failed [FAILED]
artificial failure in AfterEach
In [AfterEach] at: test/e2e/storage/testsuites/subpath.go:222
}
```

"failed [FAILED]" seems a bit redundant.

Report sizes:
```
ginkgo_report.json 48109306
ginkgo_report.xml  33052212
junit_01.xml        5854853
```

Most of the CLI output is about tests that call ginkgo.Skip at runtime: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/113538/pull-kubernetes-e2e-kind/1588169525193347072/build-log.txt

I think this all works as intended.

**Comment by onsi** [comment]
Cool!  I'm on the fence on how calls to `Skip(message)` should be handled on the console.  I might make it so that you only see the details if you are running with `-vv` - any thoughts?  It seems like it's mostly noise...

**Comment by pohly** [comment]
Perhaps show them with `-v`?

We are not using that in the CI, so the skip messages would be gone, which seems better.

**Comment by onsi** [comment]
Yes that makes sense.  I've done that now on the `timeline` branch.  I'm almost happy with where things are.  There are still a few cases where the console output is heavier than it needs to be and I'm going to look into fixing those.  After that I need to finish rewriting the reporter specs but then this should be ready to go on master... hopefully early next week!

**Comment by onsi** [comment]
The code complexity is, sadly, high - but I think I now have the default reporter output in a good place.  I'm hoping the latest code on timeline will be the final version and I'm going to work on rewriting the reporter specs next.  If you have some time to pul the latest and see if you run into any issues it would be much appreciated!

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/113538 has been updated and at first glance it looks good (skip reports are gone, failures get reported).
