### ISSUE TITLE
The AddReportEntry of junit-report is written in system-err and cannot be displayed in the body of Allure

### ISSUE THREAD

**Issue by leijux** [onsi/ginkgo#1084]
![image](https://user-images.githubusercontent.com/40145943/204151472-c9b89c69-4e24-4ea7-b7b8-6d4f36308f35.png)
![image](https://user-images.githubusercontent.com/40145943/204151488-a8593069-ecaf-4b43-91d9-01587b066ad3.png)

**Comment by onsi** [comment]
hey there - unfortunately the JUnit xml spec is not super well-defined and different systems seem to treat these fields differently.  I'm not very familiar with Allure - do you have a proposal for how to do this differently with JUnit for Allure?

**Comment by MrSantamaria** [comment]
I'm looking into something similar on my end but with Prow/Testgrid. 
From what I can tell, Ginkgo does output this in a XML accepted format. 
Locally I noticed: <system-err>&gt; ...

I'm noticing that in Prow it is being represented as <system-err>> ...
Then along the lines there is also a &lt turned into "<"

Maybe the change is for Ginkgo not to output messages that include the xml escapes?  [junit_report_test Line 118 for IE](https://github.com/onsi/ginkgo/blob/956e6d2efd6b7b53722b6d047a3941f440cb4c38/reporters/junit_report_test.go#L118)

Though I'm not sure what would be best to replace those with.

**Comment by leijux** [comment]
@onsi Can we try adding the AddReportEntry additions to the system-out tag instead of the system-err tag? https://github.com/onsi/ginkgo/blob/956e6d2efd6b7b53722b6d047a3941f440cb4c38/reporters/junit_report.go#L119

**Comment by leijux** [comment]
@onsi Thanks for your help, I'm thinking about it. I have a doubt, why AddReportEntry is output to the xml system-err tag?

**Comment by onsi** [comment]
The [JUnit XML Format](https://llg.cubic.org/docs/junit/) does not support adding rich metadata/annotations to test reports and Ginkgo specs have a lot more information than fits into the structured parts of the JUnit specification.

The compromise solution I've adopted is to inject the verbose version of the spec's timeline report (which includes every event: node entry/exit, report entries, GinkgoWriter output, failures, timeouts, By statements, retries, etc.) as a single coherent timeline.  I decided to put that block of text in `system-err` because that was a fine place for it given the limitations of the JUnit spec.  And several users of Ginkgo's JUnit format now expect it to be there.

It seems to me that `system-err` is a valid part of the JUnit spec (at least from the source I shared above) - and that several CI systems support it.  This is why I'm proposing that this is an issue in Allure - and one that i'd be happy to comment on if you open an issue with them.
