### ISSUE TITLE
ginkgo/v2 library with ginkgo-v2 cli reported leak

### ISSUE THREAD

**Issue by winkingturtle-vmw** [onsi/ginkgo#1177]
We are in the process of converting most of the CF runtime components to ginkgo/v2. We started seeing leaks reported in one of the suites we converted over. I have put together a [minimal reproduction of this issue](https://github.com/winkingturtle-vmw/mytest). This issue seems to be only relevant when we use ginkgo/v2 cli. I haven't been to successfully run the v1 library with v2 cli. It's not clear to me why this is causing a goroutine leak. We've switched over to v1 cli to get around this issue.
 
```
  [FAILED] 2 errors occurred:
        * leaktest: timed out checking goroutines
        * leaktest: leaked goroutine: goroutine 23 [IO wait]:
  internal/poll.runtime_pollWait(0x7f9b58328488, 0x72)
        /usr/local/go/src/runtime/netpoll.go:306 +0x89
  internal/poll.(*pollDesc).wait(0xc00007cc00?, 0xc0001d4000?, 0x1)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
  internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:89
  internal/poll.(*FD).Read(0xc00007cc00, {0xc0001d4000, 0x8000, 0x8000})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
  os.(*File).read(...)
        /usr/local/go/src/os/file_posix.go:31
  os.(*File).Read(0xc0000147e8, {0xc0001d4000?, 0xc0000bc8d0?, 0x0?})
        /usr/local/go/src/os/file.go:118 +0x5e
  io.copyBuffer({0x8bd720, 0xc0000bc8d0}, {0x8bda00, 0xc0000147e8}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:427 +0x1b2
  io.Copy(...)
        /usr/local/go/src/io/io.go:386
  github.com/onsi/ginkgo/v2/internal.(*genericOutputInterceptor).ResumeIntercepting.func1.1()
        /tmp/mytest/vendor/github.com/onsi/ginkgo/v2/internal/output_interceptor.go:159 +0x45
  created by github.com/onsi/ginkgo/v2/internal.(*genericOutputInterceptor).ResumeIntercepting.func1
        /tmp/mytest/vendor/github.com/onsi/ginkgo/v2/internal/output_interceptor.go:158 +0x34e
```

**Comment by onsi** [comment]
hey @winkingturtle-vmw - wonderful to hear CF is migrating over.  I'd be happy to help support the effort including being responsive on slack (I'm on the CF Open Source channel) and via GitHub issues - so feel free to let others know to reach out as well if need be.

Thanks for putting together a reproducer here.  The issue is that when running in parallel Ginkgo _does_ spawn and manage a goroutine (or two) that outlives the lifecycle of the spec.  In this case `leaktest` is finding a false positive.  The reason it passes when you run the v1 cli against v2 is.... well... because that isn't a supported way to run Ginkgo and I'm 99% sure the tests aren't actually running in parallel when you do that.  I recommend sticking with the v2 cli and fixing the issue.

I'm not sure how to fix it with `leaktest` - I haven't used it and looking through the docs there's no straighforward way to mark some goroutines as acceptable non-leaks.  You could manually filter the entries in `goroutineErrors` if need be, and ignore any matching `output_interceptor`.

My suggestion would be to drop `leaktest` in favor of [`gomega/gleak`](https://onsi.github.io/gomega/#codegleakcode-finding-leaked-goroutines).  With it your test would look like:

```go
package my_test

import (
	"time"

	"code.cloudfoundry.org/clock/fakeclock"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
	"github.com/onsi/gomega/gleak"
	"github.com/tedsuo/ifrit"
	"github.com/tedsuo/ifrit/fake_runner"
	my "github.com/winkingturtle-vmw/mytest"
)

var _ = Describe("test", func() {
	var (
		substep *fake_runner.TestRunner
		p       ifrit.Process
		clock   *fakeclock.FakeClock
	)
	BeforeEach(func() {
		snapshot := gleak.Goroutines() //captures a snapshot of current goroutines
		DeferCleanup(func() { Eventually(gleak.Goroutines).ShouldNot(gleak.HaveLeaked(snapshot)) }) //ensure no additional goroutines generated during the test have leaked.  `DeferCleanup` is new in Ginkgo V2 and allows you to generate an AfterEach from within other nodes.

		substep = fake_runner.NewTestRunner()
		clock = fakeclock.NewFakeClock(time.Now())
	})
	AfterEach(func() {
		substep.EnsureExit()
	})
	JustBeforeEach(func() {
		runner := my.NewMy(substep, clock)
		p = ifrit.Background(runner)
		substep.TriggerExit(nil)
		<-p.Wait()
	})
	FIt("runs the substep", func() {
		Eventually(substep.RunCallCount).Should(Equal(1))
	})
})
```

I'm confirmed that this works with Ginkgo V2 and `--until-it-fails`; and that it will in fact capture non-Ginkgo leaks.  `gleak` knows about the standard goroutines that Ginkgo and go testing spawn so it excludes them from its leak check.

**Comment by winkingturtle-vmw** [comment]
Thank you @onsi. Your proposed changes seems to have fixed this issue.
