### ISSUE TITLE
go routine executing test node versus go routine executing DeferCleanup?

### ISSUE THREAD

**Issue by thediveo** [onsi/ginkgo#1181]
Normally, this should not be of any concern anyway, but I've now gotten into that ugly territory where I'm locking the Go routine that executes a test node to its underlying Linux thread: this is necessary as I'm then isolating the go routine/thread to use a fresh network namespace. The main reason is because I found out the hard way that systemd-networkd and network manager are a perfect recipe for interference with my test on virtual networking.

I'm creating new virtual network interfaces in this isolated network namespace and at the same time register cleaning up these network interfaces using `DeferCleanup`. Did I mention that `DeferCleanup` is a godsend, as it allows to defer cleaning up inside test helper libraries?

As it seems, `DeferCleanup` functions seem to be run on different go routine(s) than the test nodes: is this correct? Would it be even possible to run them on the same goroutine? I'm asking to simply better understand the go routine tasking model somehow hidden in Ginkgo. I'm able to live with the current design by simply keeping a reference to the network namespace where the temporary interfaces were created, so this question is mainly out of curiosity.

**Comment by onsi** [comment]
hey @thediveo - yikes!  I'm tangentially familiar with the complex interactions between namespaces and goroutines.  good luck with it all!

Ginkgo runs every node you throw at it (`It`, `BeforeEach`, `DeferCleanup`, etc.) in a separate goroutine.  The primary reason for this is to support (per-node) timeouts and interrupts.  It takes care of all the locking/synchronization to guarantee that no two nodes ever run at the same time in a given process (though there is *one* case wehre this rule is broken: when a tiemout/interrupt occurs and the interrupted node [doesn't return in time](https://onsi.github.io/ginkgo/#mental-model-the-life-cycle-of-interruptions-and-the-graceperiod-decorator)... Ginkgo will "leak" the goroutine and start up any relevant cleanup nodes.

> Did I mention that DeferCleanup is a godsend, as it allows to defer cleaning up inside test helper libraries?

🎉 - happy to hear it's working out for you.  I've also thoroughly enjoyed using it in my projects as well.

> As it seems, DeferCleanup functions seem to be run on different go routine(s) than the test nodes: is this correct? Would it be even possible to run them on the same goroutine?

I suppose it would be possible. I could set things up so that a single worker is responsible for running the nodes synchronously on one consistent goroutine and is fed nodes to run by the Ginkgo control loop.  Then in the case where I _have_ to spin up a fresh worker to run more than one node at a time (that leaky timout/interrupt case above) I could spin up a new worker.  This would be... doable.  But also a fair bit of work and somewhat gnarly (I would be replacing the two characters "`go`" with several new lines and abstractions 😉 ).

**Comment by thediveo** [comment]
Thank you very much for the background information! Based on this I don't deem the hassle worth the effort, as you are hinting at.
