### ISSUE TITLE
ginkgo in distroless image/container

### ISSUE THREAD

**Issue by korbajan** [onsi/ginkgo#1187]
When I put ginkgo binary into the image that does not have go installed and then run container based on that image:
`exec /ginkgo: no such file or directory`
even the file is at the correct location.

How to build ginkgo binary that can be used in  images from distroless or even scratch?

**Comment by onsi** [comment]
hey @korbajan - i'm not sure how best to help you.  the `ginkgo` cli is just a go binary and should run without any additional dependencies (though, of course, if you want `ginkgo` to compile and run your tests you'll need the whole go toolchain.  if you just want to run it against a precompiled test binary you generally won't need the toolchain.).

it seems like the issue is in how your container is laid out/configured.

**Comment by korbajan** [comment]
@blgm That made the trick. Thanks!
