### ISSUE TITLE
Using spf13/pflag flagset with ginkgo.

### ISSUE THREAD

**Issue by Kush-Saxena** [onsi/ginkgo#1207]
I'm stuck at using `spf13/pflag` with ginkgo. I can see that when using `flag` library, It's working fine. However when using pflag It is not registering the flags. 

I think I'm missing something from the documentation.

**Comment by blgm** [comment]
Hi @Kush-Saxena

I'm guessing that you're adding some custom flags for your tests so that you can specify the location of resources or similar.

I've done this before using the `flag` package, for example:
```go
func init() {
        flag.StringVar(&buildDir, "buildDir", "../..", "location of the build dir")
}
```

What I'm understanding is that:
- you can do this successfully with the `flag` package
- when you try to use `spf13/pflag` instead, it no longer works

There are a number of alternative flag parsing libraries for Go. Ginkgo just [documents using the `flag` package](https://onsi.github.io/ginkgo/#supporting-custom-configuration-custom-command-line-flags), and does not document or test using any other package.

I see that `spf13/pflag` claims to be a drop-in replacement for `flag`. Which sounds hopeful for compatibility, but maybe it doesn't work when Ginkgo uses `flag` internally and the tests use `spf13/pflag`?

One option would be to stick with the `flag` package. I know it has limitations, but given that it works, you might decide to spend your efforts elsewhere.

Another option would be that if you're very keen on using `spf13/pflag`, you could invest some time in debugging what is going on. This might be easier with a small example that re-creates the problem that you could share in this issue. If the bug is on the Ginkgo side then we would be willing to accept a PR to fix that. But my caution on this would be that the incompatibility may be because the design of `flag` and `spf13/pflag` are different, and it might not be possible to reconcile them. But then again, maybe it will work with a small configuration change.

It's also possible that someone out there has got this working and might comment on this issue. Or you could use GitHub search to see whether there are any packages out there using Ginkgo and `spf13/pflag` that you could learn from.

**Comment by Kush-Saxena** [comment]
@blgm 
`ginkgo -- --server-addr="127.0.0.1:3000" --environment="STAGING"` If we can extract the passed pass-through arguments as string slice. We can surely pass that string to the `Parse()` function of any 3rd party flag library ( including `spf13/pflag` ) and hopefully that will make ginkgo compatible with other flag libraries also.

**Comment by onsi** [comment]
I believe that one piece of this puzzle has to do with how `go test` runs your test binary (the `ginkgo` cli does a lot of things, but at the end of the day it is simply invoking a precompiled `go test` binary).  In particular, `go test` calls `flag.Parse()` which expects all flags it finds to have already been registered.  This is why [Ginkgo's docs encourage you to register any additional flags in an `init`](https://onsi.github.io/ginkgo/#supporting-custom-configuration-custom-command-line-flags) which is guaranteed to be called before go test calls `flag.Parse()`.

Can `spf13` register flags with `flag` for you?  Are there any examples in the `spf13` community of successfully using it with `go test`?  I'd start there...

**Comment by Kush-Saxena** [comment]
Hey @onsi I found 2 solutions to this issue:

1. We have to call the tests by using `go test` command and passing arguments using `-args` and anything after that will automatically parsed by the flag set.
```go
func init() {
	pfs := pflag.NewFlagSet("my-pflagset",pflag.ContinueOnError)
	pfs.AddGoFlagSet(flag.CommandLine)
	pfs.Parse(os.Args[1:])
}
``` 
2. We have to call the tests by using `ginkgo` command and pass the arguments as passthrough arguments `--` .We need to get all the passed args i.e after `--` and parse them using the flag set.
```go
func init() {
	pfs := pflag.NewFlagSet("my-pflagset",pflag.ContinueOnError)
	indexOfArgSeparator := getIndexOfArgSeparator(os.Args[1:]) //It gives index of '--' and we need to parse everything after that 
	pfs.Parse(os.Args[indexOfArgSeparator+1:]) //We parse everything after that separator.
}
```

**Comment by onsi** [comment]
sounds good - glad you were able to figure out a solution!
