### ISSUE TITLE
Ginkgo V2 [TIMEDOUT] TOP-LEVEL [BeforeEach]

### ISSUE THREAD

**Issue by xtremerui** [onsi/ginkgo#1224]
Hi, we were testing bosh deployments with ginkgo v1 without issues. After switching to v2, we are seeing lots of 

```
[TIMEDOUT] TOP-LEVEL [BeforeEach] ...
[TIMEDOUT] TOP-LEVEL [BeforeEach] ...
[TIMEDOUT] TOP-LEVEL [BeforeEach] ...
```
for different tests when performing bosh tasks (creating, updating or deleting vms) each time, which we assume would pass if enough time was given.

For example:
```
		deploy := gexec.Start(cmd, GinkgoWriter, GinkgoWriter)
		<-deploy.Exited

```

will giving out error output as following:
```
STEP: [1687152042.387539625] running: bosh -n -d ... @ 06/19/23 05:20:42.387


  Task 148208 | 05:21:42 | Preparing deployment: Preparing deployment

  [TIMEDOUT] in [BeforeEach] - ... @ 06/19/23 05:22:32.465

``` 
It timeout after about 2 mins when bosh just preparing for deployment so `deploy` can't be exited.

I am wondering is ginkgo v2 becomes more time sensitive to cause this behavior and is there anyway to configure the timeout to be longer?

So far it is not clear in the doc about what the default timeout is either. Thank you!

**Comment by onsi** [comment]
hey @xtremerui one of the simple big changes between v1 and v2 is that the global timeout for a Ginkgo run now defaults to 1 hour instead of 24 hours.  You can change this back by running with `ginkgo -timeout=24h`

If that doesn't work let me know and point me at the tests if they are open source. FWIW, there is substantially better support in v2 for [spec and node-level timeouts](https://onsi.github.io/ginkgo/#spec-timeouts-and-interruptible-nodes).  These are all opt-in and not turned on by default, so they aren't the culprit for this particular issue, but they may be something you want to look into as you upgrade your suites.

**Comment by xtremerui** [comment]
`ginkgo -timeout=24h` makes the behavior to be like ginkgo v1 again. There is no more [TIMEOUT] failure. Thank you!
