### ISSUE TITLE
Adding Properties to test cases

### ISSUE THREAD

**Issue by dschveninger** [onsi/ginkgo#1227]
I was wondering if you would consider adding a Suite function like AddReportProperties to add key value pairs to the spec like AddReportEntry.  It would be a slice of key value pairs that we can use the ginkgo json file in a post execution process to better automate of the suite run data.

Let me know if you if you need more information.

As always thank you for Ginkgo and all of the help you provide.

**Comment by onsi** [comment]
I’m certainly open to this - but wondering why it can’t be accomplished with `AddReportEntry` (either each report entry is a single key-value pair or as a single report entry that is a a slice/map or key-value pairs)

**Comment by dschveninger** [comment]
We are currently using the AddReportEntry for detail messages and data for human consumption in reporting. An example, we collect supporting data related to the primary Expect so we reduce the analysis time on failure. 

We where thinking of Prefixing AddRepotEntry data to denote data to be used as properties, and filtered out for reporting, but we thought if we could increase the Ginkgo json data interface over encapsulating it would provide a better data definition in the json file without needing special processing. We produce at least 2 report formats from the json. HTML for human consumption and trx xml for internal test results storage normalization. 

The main use case is we use declarative test case definition approach and we produce dynamic specification at run time based these definitions.  Test case name have become generic and some what unclear to others. We have created a customer report generator based on the Ginkgo json file and that has help out. But the generic asserted need more specific detail like a test case description. We would like to add this data to each test case so we could have a test case description in our reports. 

If we just had this one use case I would use AddReportEntry but we also have other use cases that we would like to address. The test suites we are executing is an end to end api test suite that has other metadata we would like to attach to the test cases like: software version being tested, lab/environment being used and many more. 

This is the reason to ask for AddReportProporties feature for Ginkgo. 

Please let me know what you think and if you think this is something that would help others what would be the best way to achieve this.

thank you for your time and consideration.

**Comment by onsi** [comment]
hey @dschveninger - I just want to reiterate that I'm open to adding this sort of change.  I do, however, want to balance the size and scope of Ginkgo's interface and I want to make sure I'm understanding the usecase correctly.  Currently I'm struggling a bit to understand the reasons your usecase can't be addressed by `AddReportEntry`.

For example:

> The test suites we are executing is an end to end api test suite that has other metadata we would like to attach to the test cases like: software version being tested, lab/environment being used and many more

This can be accomplished via:

```go
AddReportEntry("SoftwareVersion", "X.Y.Z")
AddReportEntry("LabEnvironment", "Omicron-3")
```

the resulting `SpecReport` will have `ReportEntries` that look like:

```json
{
	...
	"Name": "SoftwareVersion",
	"Value": {
		"AsJSON": "\"X.Y.Z\"",
		"Representation": "X.Y.Z"
	}
}
```

there's a little bit of complexity around how the value is stored but if you're just saving off strings you can use `entry.StringRepresentation()` to retreive the value.

To make it easier to work with I'd be happy to add helper methods on `ReportEntries` so you can do stuff like `specReport.ReportEntries.EntryWithName("SoftwareVersion")`.

If part of the issue is a desire to namespace things then I'd suggest coming up with your own namespacing scheme and using that.  e.g.

```go
AddReportEntry("parameters.SoftwareVersion", "X.Y.Z")
AddReportEntry("parameters.LabEnvironment", "Omicron-3")
```

If, for some reason, you really need to have `map[string]string`  or` []string{key,value,key,value}` semantics you can also accomplish that.  For example:

```go
var m map[string]string
var _ = BeforeEach(func() {
	m = map[string]string{}
	AddReportEntry("Params", m) //adds a reference to `m` as a `ReportEntry`
})

var _ = It("adds report entries", func() {
	m["SoftwareVersion"] = "X.Y.Z" //note that we are allowed to mutate `m` later.  as long as you aren't in a separate goroutine, Ginkgo will ensure this is threadsafe
	m["LabEnvironment"] = "Omicron-3"
})
```

then to rehydrate the map in the code that processes the spec report you can:

```go
var m map[string]string{}
json.Unmarshal([]byte(entry.Value.AsJSON),  &m)
```

Given that kind of flexibility I'm wondering what might be missing in the curent implementation to enable your usecase.

Thanks!

**Comment by dschveninger** [comment]
Thank you for the code examples. We were reviewing the code and did not fully understand how to use the name as the key and raw access. We will try to see if we can use your example with a local wrapper function in conjunction with logic in our ginkgo report convertor cli to achieve our goal. 

Once again thank you for the product and the support you have given us all.

**Comment by onsi** [comment]
thanks @dschveninger - if, as you work on this, you come up with suggestions for how to adjust/add to the various interfaces/structs (`SpecReport`, `ReportEntries`, `ReportEntry`, etc...) to make them easier to use please let me know!
