### ISSUE TITLE
Make it possible to flush output via newline in between tests

### ISSUE THREAD

**Issue by onsi** [onsi/ginkgo#1347]
Some CI systems only flush output when a newline is observed.  This makes it hard to see Ginkgo's progress when running without `-v`.  A new mode that forces Ginkgo to emit a newline between each spec report (even if that report is just "`o`")  would resolve this.

/cc @pohly

**Comment by pohly** [comment]
This is the gist of it. Note that we haven't actually verified that a newline will help, but it seems likely.

While you are at it, a mode where not even the `o` or `S` gets printed might also be useful. When I run `-focus=one-particular-test`, the screen fills up with `S` characters simply because we have so many tests in the Kubernetes E2E suite.

**Comment by pohly** [comment]
Or make it so that just the `S` gets skipped (pun intended). The `o` is useful when running a few tests.

**Comment by onsi** [comment]
sigh - it only took 3 months but `--silence-skips` and `--force-newlines` are both now available on master.  i'll be cutting a release shortly. please give it a try when you have time and lemme know if it helps.

**Comment by onsi** [comment]
2.18.0 is out and includes this

**Comment by onsi** [comment]
woops - didn't mean to close it!

**Comment by pohly** [comment]
This works as expected and does indeed help with watching progress in Prow. Thanks!

I think this can be closed.

**Comment by onsi** [comment]
wonderful, glad to hear it!
