### ISSUE TITLE
Timeout expiration doesn't stop running functions

### ISSUE THREAD

**Issue by lavalamp** [onsi/ginkgo#165]
Essentially, it looks like the timeout feature is _only_ good for detecting deadlocks, and it's _not_ good for stopping slow tests.

Example problems:
- If a slow function eventually fails, the failure is counted towards the wrong test.
- If a slow function eventually completes and calls `close(done)` it will panic with a double-close error.
- Since AfterEach is run when the timeout happens and the body of the test may still be executing code, it is impossible to reason about the state of the test in AfterEach to do proper cleanup.

Unfortunately I don't have a good suggestion for fixing this. Ideally a timeout expiration would cause the offending goroutine to get killed, but there's no facility for doing that in the language. I suppose something like panicing on Logf/By/etc statements when the test has been timed out and then catching that somewhere might be a possibility, but that doesn't sound like a complete solution.

**Comment by onsi** [comment]
@lavalamp - there is no way for one goroutine to kill another goroutine.

If and when Ginkgo 2.0 is written I will almost certainly be removing the `done Done` async test feature.  It seemed like a good idea at the time when I came up with it but our experience with it (across several teams using Ginkgo to build all sorts of interesting and complicated async tests) is that its utility is severely limited and it opens up all the issues you've encountered.  At the root of the problem is the fact that, as I said, it is impossible for one goroutine (the one doing the timing) to kill another (the one actually executing).

At the very least I should update the docs to reflect this.

In lieu of Ginkgo's built-in async testing support I strongly recommend using Gomega's `Eventually` to do all async testing instead.  It gives you much better control over asynchronous operations and allows you to be more explicit about what, exactly, is timing out.

If you point me at some code that uses `done Done` I can try to help show you how to convert it.
