### ISSUE TITLE
Question: Modifying benchmark output to show milli/micro/nano seconds

### ISSUE THREAD

**Issue by duskhacker** [onsi/ginkgo#176]
I'm interested in seeing my benchmark output reported in milliseconds instead of seconds. I've looked somewhat at the code, but there doesn't seem to be an easy way to do this without modifying the internal source. I've looked at writing a reporter, but that doesn't seem to do what I want, I seem to be able to write a reporter that outputs the actual measurement in the units I want, but I don't see a way of modifying the label 's' -> 'ms'. 

Is this possible, and if yes, could I get some pointers on how to do this without much fuss?

**Comment by onsi** [comment]
hey @duskhacker sorry for the delay.

Unfortunately the `Measure` code is fairly opinionated (too opinionated) around how it records and represents time.

One approach could be to make it possible to specify the units and a precision for a benchmark:

1. Add a new method to the [`Benchmarker` interface](https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L175-L178) called

```
RecordValueWithPrecision(name string, value float64, units string, precision int, info ...interface{})
```

2. Add `Precision int` to [`types.SpecMeasurement`](https://github.com/onsi/ginkgo/blob/master/types/types.go#L87-L103)

3. Update [`getMeasurement`](https://github.com/onsi/ginkgo/blob/master/internal/leafnodes/benchmarker.go#L44-L67) to accept and pass in the `FormatString`.  Add `RecordValueWithPrecision` and update `Time` and `RecordValue` to insert the existing precision (`3`).

4. Update [measurementReport](https://github.com/onsi/ginkgo/blob/master/reporters/stenographer/stenographer.go#L487-L542) to honor the measurement's `Precision` instead of the hardcoded `("%.3f")`.

---

This way you can `RecordValueWithPrecision("foo", duration.Milliseconds(), "ms", 2)  (note you'll have to do the timing yourself).

You probably don't need the `Precision` piece so you could just do `RecordValueWithUnits(name, value, units)` but I think `Precision` could be useful in general.

Final alternative: add a new `TimeWithPrecision()` method to `Benchmarker`.  Maybe this could take "s", "ms", "µs", etc.. maybe it just takes an integer precision.  Not sure but happy to think it through with you if you'd like.

**Comment by onsi** [comment]
Closing this out for now.  @duskhacker lemme know if you'd like to work on this/reopen the issue.
