### ISSUE TITLE
ginkgo -race detector exits 0 

### ISSUE THREAD

**Issue by evanshort73** [onsi/ginkgo#178]
When running tests with ginkgo, @robdimsdale and I are seeing the race detector exit with 0 even though data races are found. Unlike Issue #123 we are able to see output describing the race condition, and unlike Issue #78 we have no focused or excluded tests. We are passing the following options to ginkgo:
```
CGO_ENABLED=1 ginkgo -race -r -p
```
The output is as follows. Let us know if you need more info.
![screen shot 2015-08-24 at 2 38 25 pm](https://cloud.githubusercontent.com/assets/7635837/9453346/a208b7c6-4a6e-11e5-89e1-c7e9d859aac5.png)
![screen shot 2015-08-24 at 2 37 30 pm](https://cloud.githubusercontent.com/assets/7635837/9453349/a53d6144-4a6e-11e5-940f-b743ab6fd680.png)

**Comment by robdimsdale** [comment]
to clarify, the `CGO_ENABLED=1` is because we're running in a container where golang was compiled with `CGO_ENABLED=0` - we see the same issue when running locally in OSX with golang installed via brew (and no additional flags)

**Comment by onsi** [comment]
Yep.  Try a plain vanilla (xunit style test) with the race detector enabled and you'll see the same thing,  the race detector does not cause the test suite to fail.

I think the idea is that the race detector is generic and can run in running code, not just tests.  In the running context it doesn't cause the process to exit, but simply emits to stdout.   I think that behavior carried over into go test: there's no notion of the test failing because of a race.

Please tell me if I'm wrong though.  This was the case when last I played with it.

I did put something awful together where the ginkgo test runner would monitor test output for "WARNING: DATA RACE"  but I think I ended up abandoning that code (surprised?).

**Comment by onsi** [comment]
Actually.  I might be misremembering.  In any event, `go test --race` now exits with `66` on go 1.5 and the latest Ginkgo does honor this exit code and mark the test suite as failed.  Maybe try upgrading both?

**Comment by robdimsdale** [comment]
We are using the latest ginkgo, and we will upgrade to golang 1.5 soon - we can report back at that point. Happy to close this issue, or we can leave it open to capture the results of further investigation.

**Comment by onsi** [comment]
Do please keep it open and lemme know what you find!

**Comment by robdimsdale** [comment]
Roger that

**Comment by robdimsdale** [comment]
After upgrading to go 1.5.1 and using the latest version of ginkgo (`1b59c57`) we observe that race conditions cause ginkgo to report failure, as expected.

Feel free to close this issue.

**Comment by onsi** [comment]
woot!
