### ISSUE TITLE
Build tag produce an error

### ISSUE THREAD

**Issue by piotrkowalczuk** [onsi/ginkgo#180]
Hi, 

my test file starts with

```go
// +build development
```

when i call ginkgo from package directory:

```bash
Failed to run test suite!
	fork/exec /Users/..../Projects/go/src/.../email/email.test: no such file or directory
Ginkgo ran 1 suite in 100.592272ms
Test Suite Failed
```

without tag it works correctly

**Comment by onsi** [comment]
Sorry for the delay.  It looks like the `ginkgo` cli is detecting that a test suite exists in the given directory (it does this by simply looking for a file that looks like `*_test.go`).  However, since you aren't running `ginkgo -tags=development` Go doesn't find anything to compile and ends up bailing.  Ginkgo then complains that it can't find the test file it expected to find.

I could fix it by having Ginkgo ignore missing test files but I'd be concerned of accidentally masking an error.

I'm assuming you are running `ginkgo -r`.  If so, you have two immediate options:

1. Always run `ginkgo -r -tags=development`
2. Always run `ginkgo -r -skipPackage=email` to tell Ginkgo not to run the `email` package

Onsi

**Comment by akutz** [comment]
Hi @onsi,

This hit me as well. My solution was to ensure there's always a `*_suite_test.go` file without any tags, and then one or more `_test.go` files with tags I want to enable/disable. This way `ginkgo` can always fine at least the `*_suite_test.go` file to compile. The unwanted side-effect is that `ginkgo` _thinks_ there is an empty test suite as well as produces an empty coverage result (assuming coverage is enabled).
