### ISSUE TITLE
Is it possible to start fewer nodes when few tests need to be run?

### ISSUE THREAD

**Issue by stevekuznetsov** [onsi/ginkgo#184]
We have `ginkgo` set up to use many nodes to parallelize testing. When there are few tests (<7) we still see seven nodes spawned for parallel processing. How do we ensure that if there are few test cases we do not spawn more nodes than we have tests to run? Usually we run with a `focus` that restricts us to 1 or 2 specs out of 20-30.

**Comment by onsi** [comment]
Sorry for the delay :/

When tests are focused ginkgo doesn't do any work to distribute them across the number of nodes you are spinning up.  In principal this is possible though, fwiw, the excess nodes are basically no-ops.

If you're focusing tests why not just run without -p?

**Comment by stevekuznetsov** [comment]
Potentially our `-focus` flag will grab many specs. We are using it to select functional areas of code. We still want to run in parallel for performance.

**Comment by stevekuznetsov** [comment]
@onsi Are you saying that currently there is no way to change the behavior so it does not start nodes that only run `nop`?

**Comment by onsi** [comment]
The `ginkgo` cli know nothing about your tests.  It does not compute the tree of tests and has no idea how many tests will end up running.  It simply compiles (if necessary) and launches test processes.  

These processes then each compute the tree of tests then filter it to apply the `-focus` flag or any programmatic focus (e.g. `Fit`).

When running in parallel mode, the `ginkgo` cli launches `N` processes is specified via `-nodes=N` or the number of CPU cores - 1 if specified via `-p`.  Each of these processes is assigned an index and told how many processes are running (`N`).  Each ginkgo process then computes the tree (identically) and selects the relevant subset of tests to run.

**Here's what's easily doable**: today the way the subset of tests is computed is very naive.  If you only focus 5 out of 20 tests Ginkgo doesn't try to distribute the 5 tests evenly across all nodes.  Instead it distributes 20 tests evenly across all nodes and whether or not your 5 get evenly distributed is a crapshoot.

It would be fairly straightforward to have the individual test nodes distribute the focused tests more uniformly.

**Here's what's difficult**: controlling the *number* of nodes to spawn.  Since the `ginkgo` cli doesn't know anything about your tests it can't compute the number of nodes correctly.  As a result you *could* end up with a number of nodes that don't run any tests but simply launch the `BeforeSuite` and then the `AfterSuite`.

**Comment by stevekuznetsov** [comment]
@onsi  That makes sense. We've changed our invocation of `ginkgo` so that the user has to specify when they want parallelism, so that solves our problem.
