### ISSUE TITLE
Comparing different signs is a failure?

### ISSUE THREAD

**Issue by elliotchance** [onsi/ginkgo#186]
Not sure if this is a bug or it exists for a reason, but the following code will fail:

```go
Ω(lexer.Offset).Should(Equal(1))
```

Whereas, this will pass because the types are now the same.

```go
Ω(lexer.Offset).Should(Equal(uint(1)))
```

**Comment by tjarratt** [comment]
This occurs because ginkgo has to guess the type on the right hand side. Because Equal receives a value as interface{} it needs to guess what type you actually meant, and probably defaults to int. 

In my tests, I often use the BeEquivalentTo matcher because it's more forgiving and compares int values of different types. 

Hope this helps!

Sent From A Very Small Keyboard

**Comment by onsi** [comment]
`Equal` uses Go's `reflect.DeepEqual` which is pretty persnickety about types.

When comparing numbers I prefer [`BeNumerically("==", 1)`](http://onsi.github.io/gomega/#benumericallycomparator-string-compareto-interface).

**Comment by elliotchance** [comment]
Ah thanks, looks like `BeEquivalentTo` is what I need - cheers guys!
