### ISSUE TITLE
Cover profile for focus tests

### ISSUE THREAD

**Issue by jasonkeene** [onsi/ginkgo#205]
When Describe, It, etc are focused `ginkgo -cover` does not output a coverprofile at all. It would be nice if, when you focus tests, you get coverage statistics for just the tests that run. That would allow developers to easily pinpoint what code is being exercised by what tests. If this feature is not desired then I'd prefer some sort of message in the output letting you know that -cover is not supported while tests are focus.

**Comment by onsi** [comment]
Sorry for the delay.  I've looked into this and it is, in fact, an issue - but I don't think it's fixable :/

Ginkgo tests exit with a "special" status code (197) if the user applies a programmatic focus (i.e. `FDescribe`, `FIt`, etc...).  The intent with this non-zero exit code is to ensure that CI systems will fail the test if there is a programmatic focus - it is almost always a mistake to commit a focused test!

Computing the coverage statistics is completely handled by `go test` which `ginkgo` calls out to.  Apparently `go test` does not compute coverage stats if the test process exits non-zero (or, perhaps, if it exits prematurely as Ginkgo must in order to set the exit code).  As far as I can tell, there's no way to exit 197 *and* get `go test` to emit coverage stats.

If, however, you use the `ginkgo --focus=<REGEXP>` flag Ginkgo does *not* exit with the special status code.  The idea here is that you've explicitly configured CI to only run a subset of tests.  In this case, `ginkgo --cover` *does* work.

**Comment by robdimsdale** [comment]
@jasonkeene given the above comment, this is an issue that we can't fix in ginkgo, so I'm going to close this issue. Please feel free to open a new issue if you have any further questions.

**Comment by jasonkeene** [comment]
@robdimsdale Yeah, I was thinking about closing this a little while ago as well. I've been using --focus and a few other work arounds to get the cover profiles I need. If these work arounds don't work in the future I'll reopen. Thanks!

**Comment by joefitzgerald** [comment]
@onsi Sorry to resurrect this from the dead, but perhaps if there were a flag we could pass to suppress the `197` exit code, this could be used by integrations with editors to show coverage for focused blocks?

Obviously the default behavior should continue to be a non-zero exit code, but it feels like this would be a nice compromise to allow for both modes of use?

Are you open to a PR for this?

**Comment by onsi** [comment]
hey @joefitzgerald - yes a PR would be great!  How about we add a flag like `--exitCodeOnFocus=197` (or a better name if you can come up with one?)?  Please be sure to submit a PR to the `gh-pages` doc branch too please.  Thanks!

**Comment by joefitzgerald** [comment]
@onsi I chose an environment variable to permit this to work effectively when integrating with `go test [args...]`. Hope that's OK.

**Comment by onsi** [comment]
@joefitzgerald is this issue having to blam on an extra arg at the end?  env variable is nbd

**Comment by carldunham** [comment]
This appears to have returned. If I run
```
% GINKGO_EDITOR_INTEGRATION=true ginkgo -cover -coverprofile=coverage.out
```
with a single `Context` changed to `FContext`, I get no `coverage.out` file. If I change it back and run it again, I now get the coverage file.

Happy to open a new issue and provide more detail if needed, but seems easy to reproduce.

```
% ginkgo version
Ginkgo Version 1.4.0
% go version
go version go1.9.4 darwin/amd64
```

**Comment by nodo** [comment]
@carldunham I wasn't able to reproduce your problem with the same go and ginkgo version. However, feel free to open a new issue with more details if you feel would be useful. I don't have much context on this, but I am happy to help you figure out what's the issue.
