### ISSUE TITLE
Add option to "continue-on-fail" in Describe

### ISSUE THREAD

**Issue by tarnold55** [onsi/ginkgo#219]
Describe block will panic on failed assertion aborting the remaining tests.  There will be test blocks that want this behavior and other test blocks that will want to continue on failure.  I don't see anyway to continue if previous tests in the describe block fail.

**Comment by robdimsdale** [comment]
@tarnold55 you are talking about assertions in `Describe` but I assume you mean assertions in `BeforeEach` and potentially `BeforeSuite`.

I've not come across a situation like this so I can't yet see the use-case. Could you give an example of a failing expectation in a `BeforeEach` that you're happy to ignore? The reason I'm unsure about this is because I view the `BeforeEach` as a way of setting up the environments, and the various assertions that take place inside it as a mechanism to ensure the environment is the way we desire. A failing assertion here means the environment isn't in the state I expect, so I don't want the test to run.

Could you restructure your tests such that you don't share a common `BeforeEach` and instead use multiple `Context/Describe` blocks, each with their own `BeforeEach` to make the environment setup deterministic?

You may also want to look at the `-keepGoing` flag if you haven't seen it already. It will at least run all the tests even if the `BeforeEach` fails.

**Comment by onsi** [comment]
@tarnold55 perhaps you can share a code snippet that illustrates the issue you are seeing?  As a rule all assertions should be in a `BeforeEach` Or `It` Never in he body of the `Describe/Context`.

**Comment by tarnold55** [comment]
All my asserts are in It and the Before.. and After... blocks.  I found an issue where I had a nested It and the outer It had a failure.  I fixed that and I got the behavior I expected.  This issue was user error.  Thanks for the quick response.

**Comment by onsi** [comment]
Wait.  `It`s should never be nested - the behavior is basically undefined...
