### ISSUE TITLE
Optimal distribution mechanism of ginkgo executable?

### ISSUE THREAD

**Issue by robdimsdale** [onsi/ginkgo#240]
I'm wondering if `go get` is still the best mechanism for obtaining the latest version of the ginkgo binary? I've had success in building binaries and attaching them to github releases. Examples include https://github.com/robdimsdale/wl and https://github.com/robdimsdale/garagepi

Somewhat orthogonal is the question of vendoring third-party dependencies; in my experience once you get a couple of external dependencies it becomes valuable to lock down their versions. The recent work in `GO15VENDOREXPERIMENT` should allow us to keep vendoring of any third-party dependencies separate from the question of how we build and distribute the binaries.

The impetus for this question is #239 - this PR wants to introduce a third-party dependency which will prevent the ginkgo executable from being able to be built out of the box.

@onsi thoughts?

Thanks,
Rob

**Comment by jayunit100** [comment]
- Sounds like you're suggesting that we start using `Godep`s ?   
- I would agree its pretty much the standard  if 3rd party reps are needed.

**Comment by jayunit100** [comment]
Actually, come to think of it - we already have one external deep: Gomega.  So realistically, I guess we really need godeps already.

**Comment by onsi** [comment]
I'd prefer to avoid Godep/what-have-you -- will respond on the other issue.

**Comment by jayunit100** [comment]
Maybe it is premature for godep. 

In any case @onsi maybe if we (you :)) Added the code policies that would help set things like this in stone (I.e. Regarding external deps, preferred build, and test process) since gomega and protobuf and so on are dependencies, I'm sure this issue will be brought up again ... And I'm sure ginkgo will enjoy more Prs and growth in the future , so it's good to have a doc like that in place.

**Comment by robdimsdale** [comment]
Continuing the current pattern of copying dependencies means we can continue using `go get` as the distribution mechanism, so I'll close this issue now.
