### ISSUE TITLE
Slow tests?

### ISSUE THREAD

**Issue by gabrielf** [onsi/ginkgo#258]
Hi, we use Ginkgo for our unit tests. The tests are executed fast (0,5s) but to run all the tests are slow (28s).

Are the test files are compiled one by one instead of in one go? Is there any way to speed up the test run?

**Comment by emidander** [comment]
I would also like to know this! Test performance appears to have become worse with Go 1.6.

**Comment by onsi** [comment]
ginkgo first identifies all packages to test and then compiles the packages using `go test -c` and then runs the compiled binaries as they compile.  the packages are compiled _in parallel_ in order to speed up compilation.  you can try using the `ginkgo --compilers=N` flag to control the number of parallel compilers - it _might_ help to use low `N` (default is number of CPUs).

compilation got _really, really_ slow in 1.6.  I'd love help digging into this and whether or not there are alternative ways to speed compilation up.

**Comment by onsi** [comment]
Am closing this out as I believe test compilation is faster in more recent versions of Go.
