### ISSUE TITLE
BuildFlagArgs is not tested

### ISSUE THREAD

**Issue by lavalamp** [onsi/ginkgo#263]
If one adds fields to the config struct, no test fails if they are not also added to BuildFlagArgs.

**Comment by tedsuo** [comment]
I feel like we should be able to refactor this so that the two cannot be decoupled. For example, if the base names for the flags were tags on `GinkgoConfigType` and `ToArgs(prefix string)[]string` and SetFlags(flagSet *flag.FlagSet, prefix string, includeParallelFlags bool)` became methods which used the tags. 

Much of this code hasn't really been refactored since the original spike, so there are probably a couple of other refactors that would have to come along with it (separating out `DefaultReporterConfig` for example). I don't know how far we want to go, as this code rarely needs to change, but in general the factoring around flags and configuration is a bit crap at the moment.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I've overhauled how flags are processed in [v2](#711)

I'm going to close this for now, but feel free to reopen it if you'd like.
