### ISSUE TITLE
-gcflags support in Gingko test runner?

### ISSUE THREAD

**Issue by allenluce** [onsi/ginkgo#271]
I'd like to use the Ginkgo test runner do not know how to pass `-gcflags=-l` through to the compiler through it. Is there currently a way to do this?

**Comment by onsi** [comment]
hey @allenluce - i've been adding additional build flags in as they come up.  would you be up for submitting a PR to add `-gcflags`?  The code would basically need to mirror the existing support for `-tags` (there's a [commit](https://github.com/onsi/ginkgo/commit/6d2c60e821e0e33f45c0bb3a1c19970c6288a1f0) that added this but it is likely out of date at this point as I've moved around how test suites are compiled).

While I'd love to see this flag (and any other relevant build flags) get added into the core (and perhaps there's a way to not have to add them manually?  not sure...) there *is* a way for you to use the Ginkgo test runner.  Check out the [precompiled tests](http://onsi.github.io/ginkgo/#precompiling-tests) section of the documentation.  Instead of using `ginkgo build` you can just call `go test -c -gcflags` and then pass the resulting binary to `ginkgo`.

**Comment by allenluce** [comment]
Yeah, totally. I didn't actually look at the commit you referenced until after I'd done this, but hopefully it's not too off-track.

**Comment by onsi** [comment]
I think you've got it.  will merge it in once travis goes green.

**Comment by allenluce** [comment]
Working great, thanks!
