### ISSUE TITLE
CLI issue when a package's only test file uses a build tag

### ISSUE THREAD

**Issue by rosenhouse** [onsi/ginkgo#290]
Given your package has only a single `something_test.go` and that file begins with

``` go
// +build sometag

package something
...
```

When you run `ginkgo` on that package

Then things go sideways:

```
Failed to compile program: output file "/var/folders/blah/blah/T/ginkgo126282887/program.test" could not be found
```

Minimal repro here: https://github.com/rosenhouse/ginkgo-build-flags-issue

If I wanted to try to fix this, would you suggest that I start..... [here-ish](https://github.com/onsi/ginkgo/blob/master/ginkgo/testrunner/test_runner.go#L60)???

**Comment by onsi** [comment]
Hmm.  interesting.  what should the desired behavior be?  I guess it should just ignore the package as there are no matching tags?

Starting [there](https://github.com/onsi/ginkgo/blob/master/ginkgo/testrunner/test_runner.go#L60) might be problematic as `go test -c` exits 0 and just says:

```
?      	github.com/rosenhouse/ginkgo-build-flags-issue/program 	[no test files]
```

We'd need `ginkgo` to somehow detect that "hey everything's actually OK, but no test binary was generated because there was nothing to actually do".  Options for doing that:

1.  If `go test -c` exits `0` *and* there is no artifact generated.  Move on.  Not sure what sort of false positives this lets slip through, tbh.
2. Capture and grep the output of `go test -c` for `[no test files]` and move on if detected.

*Alternatively* you could start [here](https://github.com/onsi/ginkgo/blob/master/ginkgo/testsuite/test_suite.go#L48) and pass in the `--tags` arg and come up with a better mechanism to identify whether or not there is a test in the package that matches all tags.

**Comment by onsi** [comment]
@rosenhouse any thoughts on this?  Is it still an issue you're running into or have you found a way around it?

**Comment by rosenhouse** [comment]
Ah.... I can't even remember which codebase I was in where this occurred.  Closing for now.   Hope you're enjoying your time off!
