### ISSUE TITLE
Specify serial test in parallel suite

### ISSUE THREAD

**Issue by Random-Liu** [onsi/ginkgo#294]
Is it possible to add a spec `SIt()` which specifies whether the test should be run in serial?

And when ginkgo framework runs the test suite, it runs all normal test in parallel first, and then run all serial test one by one.

In Kubernetes, we have many different test suites for different test purposes. Ideally, we want to group test into different suites by different purposes. However, currently for each suite we have to create a separate serial suite, which is troublesome.

If I want to package the test as a product to the user, I have to tell user to run normal test by default and add some special flag to run serial test separately, which is not a good ux.

One possible option is to manually run `ginkgo` twice with different flags, but the test result will be separated...

**Comment by vito** [comment]
Is the intent for the tests to be run in the given order (possibly preserving side-effects between them), or just not in parallel with each other?

Would it make more sense to have a `Serial` wrapper around `It`s instead, and allow `Serial` blocks to run concurrently (while running their contained `It`s serially)? Otherwise it feels like `SIt` could scale poorly as more are added that aren't strictly related to one another.

How would this compare with merging all the `SIt`s into one `It` and using `By` for the individual examples?

**Comment by onsi** [comment]
good question @vito 

@Random-Liu perhaps you can help us understand *why* some k8s tests need to be run in series?

**Comment by Random-Liu** [comment]
> Is the intent for the tests to be run in the given order (possibly preserving side-effects between them), or just not in parallel with each other?

For test which needs to be run in given order, at least we can do them in one spec. The problem is that for some test we don't want it to run in parallel with the other test.

I understand that it is recommended to make each spec independent, but sometimes it's quite hard. We usually just run many tests against a Kubernetes cluster, instead of creating a new cluster (create VMs, deploy K8s etc.) for each test.

In that case, if a tests has some side effect (for example it will restart a component, or temporarily change system configuration), or has some assumption about the cluster, it has be run separately.

**Comment by tedsuo** [comment]
I don't think it's good UX to pass command line flags that are then ignored by the program. You will find a lot of complexity in the corner cases. For example, what happens when I say `-p -randomizeAllSpecs` and there is a hidden control layer that says "run these particular tests in serial"? Regardless of the answer, it's not obvious and it's hard to document.

Currently, command-line flags and ginkgo test structures are orthogonal. For example, I can choose which specs are pending by modifying the test structures, and I can control what to do about those pending specs by setting command line flags. But I can't "unpend" a spec from the command line. This clean separation should remain in ginkgo's UX. Allowing both test structures and command line flags to control whether a suite is run in parallel would violate this separation. To show how weird this would be, imagine if we also added a "PDescribe" that always ran those tests in parallel, even if you configured your test run to be serial. Personally, I would *not* like that.

But! Just as we have guards such as `-failOnPending` to prevent accidents in CI, it *would* be helpful to have a guard in our test suite to prevent a CI accident from occurring when an unparallelizable test suite is run in parallel mode. This would give clear feedback to the user that they have misconfigured the test run, rather than having it fail mysteriously (or worse, pass mysteriously). Currently, you would have to fool around with `config.GinkgoConfig.ParallelTotal` to accomplish this. Adding a `config.GinkgoConfig.Parallel` boolean would make that cleaner. Possibly a control structure such as `SDescribe` would help as well. In this case, `SDescribe` would do nothing but fail the suite if it is run in parallel mode.

> One possible option is to manually run ginkgo twice with different flags, but the test result will be separated...

I believe this is the right approach. It easy enough to have a script that acts as a single command, for users who don't want to delve into the details around configuring ginkgo. In your usecase, what aspect of the test results being separated would be problematic? If handling the output is the only problem, perhaps there's a clean way to solve this.

**Comment by XenoPhex** [comment]
lighting this conversation up again.

Is there any chance there could be a `--serialPackages=...` flag that would allow all packages but the ones specified to run in parallel, but the specified runs in series. We also have a suite of integration tests that change shared external state, so we would like these tests not to run in parallel, but we also want to just have a single `ginkgo -r integration` command.

**Comment by alexbrand** [comment]
+1. Would be great to be able to specify a subset of specs that should run serially.

**Comment by onsi** [comment]
I prefer the compromise approach of saying that test authors should separate out their serial-only tests into a separate package.  @XenoPhex how important is it that we maintain the single `ginkgo -r`?  You can get close to what you want with:

```
ginkgo -r -p -skipPackage=serial
ginkgo serial
```

**Comment by onsi** [comment]
Closing this out for now.

**Comment by XenoPhex** [comment]
Oh man, sorry, i must have missed your reply! The example you gave is what we currently do.

While it's not terribly important, it would just make it easier for us when we are describing our testing procedure with others (eg 'run the following command to run all of our integration tests' as opposed to these several commands).
