### ISSUE TITLE
Allow for testing of SIGINT and SIGTERM handling

### ISSUE THREAD

**Issue by mnussbaum** [onsi/ginkgo#304]
I'd love to have the ability to test my applications handling of `SIGINT` and `SIGTERM`, but sending those signals to the application during the test suite causes ginkgo to [fail and exit the test suite](https://github.com/onsi/ginkgo/blob/master/internal/specrunner/spec_runner.go#L192).

I'm not sure exactly what mechanism I'd like to see, but perhaps a way to register your own signal handlers to override ginkgo's defaults would work.

**Comment by onsi** [comment]
hey @mnussbaum this feels like an edge case to me.  most suites I've seen that test signal handling are integration tests that spin up the binary and manipulate it externally.

rather than add a feature to ginkgo perhaps you can use `signal.Reset` in a `BeforeSuite` and then let your code register its own signal handler?

my concern with adding something that does this for you in Ginkgo is it will have the surprising side-effect of `ginkgo` not cleaning up in response to `SIGINT` and `SIGTERM`.

**Comment by williammartin** [comment]
@mnussbaum Just doing some housekeeping. Did you get a satisfactory resolution to this, or do you still want some kind of feature enhancement? Thanks

**Comment by mnussbaum** [comment]
Sorry to drop off the thread. I no longer need this feature for anything so I'll close out the issue
