### ISSUE TITLE
When running in parallel, some nodes receive tests unevenly (take much longer)

### ISSUE THREAD

**Issue by smarterclayton** [onsi/ginkgo#333]
We run a very large number of tests at very high parallelism (N=25) with each test taking between 5s and 3m to run.  Since I believe (at least based on reading the code and other comments) that tests are determined up front based on consistent seeds, runs that would take 10m if workers were able to grab from a shared queue end up taking 20m or more.

Is there a cheap / easy way to divide up jobs more fairly short of building a more complex job distributor?

**Comment by onsi** [comment]
Yeah, a shared queue _would_ have been a much better approach to how Ginkgo doles out tests to the workers.  At this point that approach will take some work (it's definitely doable within the exiting architecture but I expect it's a solid ~20-30 hours of effort at least).

For now there is one hacky trick you can use that will likely improve your test performance _on average_:

When Ginkgo randomizes tests it's actually only randomizing the outer `Describes` and `Contexts`.  This is done intentionally so that clustered failures within an outer `Describe` or `Context` don't appear distributed all over the place (imagine writing unit tests and running `ginkgo` as you test drive your code - seeing failures randomly interspersed throughout the test suite is potentially confusing to the developer trying to debug an issue).

Unfortunately this has a negative side-effect for parallel tests.  It's _often_ the case that slow tests get clustered within a given `Describe` or `Context`.  When tests are distributed in parallel each node computes a consistent order and then takes a slice of tests determined by that node's index.  This means the contents of outer `Describes`and `Contexts` aren't distributed _across_ nodes but tend to land on individual nodes.  If you have a particularly slow set of these land on one node you'll see that node take much longer than others.

Which is a long-winded way to point you toward `ginkgo --randomizeAllSpecs`.  This will randomly distribute *all* test cases across the nodes.  Nowhere near as good as a shared queue but in practice it can trim a lot of time off of your test suites.  The only catch is the time savings aren't *consistent* - depending on the random seed different tests will land on different nodes.

Not a great answer but something that's available today.  I'll need to carve out some time to get to the shared queue work which I think will be super valuable...

**Comment by onsi** [comment]
...actually - i found a quicker way to do this.

can you try out the `parallel-queue` branch?  you'll need to rebuild the CLI.  it doles out tests via a shared queue and you should see a significant speed bump.

**Comment by smarterclayton** [comment]
Will give it a try

**Comment by smarterclayton** [comment]
Does the client half (the part in the tests) have to change at all?  Still seeing wildly variable times (between 460 and 615 seconds) - definitely using the parallel-queue binary to launch, but did not update the vendored client site.

**Comment by onsi** [comment]
yes you need to make sure you're:

(a) using a recompiled ginkgo cli (so make sure to `go install github.com/onsi/ginkgo/ginkgo` after checking out the `parallel-queue` branch).
(b) building your test suite against the `parallel-queue` branch (so update your vendored dependencies if need be).

**Comment by smarterclayton** [comment]
Figured, will retry.

**Comment by smarterclayton** [comment]
Ran this several times with code on both sides and was seeing times be fairly consistent - 480s-530s.    That may be near the theoretical max for this workload since I've saturated the workload.  Note the very nice bell curve - other runs are rougher on both sides.

<img width="649" alt="screenshot 2017-03-14 01 58 03" src="https://cloud.githubusercontent.com/assets/1163175/23887706/e474d14e-0859-11e7-9a08-55084c23a923.png">

I think this is definitely bringing in the long tail as expected.

**Comment by onsi** [comment]
Cool.  I confess I can't quite understand the plot (the x-axis is time, what's the y-axis?, is each line a different run?  is the light-blue the old code and the others the new code?)

in any event, i'll likely merge this into head soon.  any objections on your end? did you notice any instabilities/issues?

thanks for the idea nad for validating it!

**Comment by onsi** [comment]
this is now on master.  please close the issue out @smarterclayton if you think it can be resolved.

**Comment by smarterclayton** [comment]
The graph above was CPU per machine of two successive runs of the full kubernetes+openshift e2e suite against a four node cluster, where each line is a separate 2core machine.  Before, it was very jagged with a peak, then a set of staggered sub peaks afterwards.  This is very smooth, with much better saturation.

**Comment by onsi** [comment]
Looks like e2e is happy.  Gonna close this out @smarterclayton - open it back up if you see any issues.

**Comment by smarterclayton** [comment]
Confirmed this is working as expected.  Thanks - cut 15-20% off the long tail of the runs.
