### ISSUE TITLE
fixCompilationOutput breaks compilation output 

### ISSUE THREAD

**Issue by benmoss** [onsi/ginkgo#357]
Here's what `go build` reports:
```
$ go build ./api
# github.com/pivotal-cf-experimental/davos/database
database/client.go:113: notice.ProductNotices undefined (type ProductNotice has no field or method ProductNotices)
```

And here's what Ginkgo reports:
```
$ ginkgo ./api
Failed to compile api:

# github.com/pivotal-cf-experimental/davos/database
api/database/client.go:113: notice.ProductNotices undefined (type ProductNotice has no field or method ProductNotices)
```

It looks like the problem being solved by the `fixCompilationOutput` function is causing this problem in turn.

**Comment by onsi** [comment]
Hey @benmoss - what's the problem specifically?  `fixCompilationOutput` exists so that when you run `ginkgo -r` you get clear locations of all your compilation failures.  It basically tries to get you a full relative path from CWD into each failure (i.e. `api/database/client.go` instead of `database/client.go`)

**Comment by benmoss** [comment]
Yeah, our code doesn't live in `api/database/client.go`, it's just in `database/client.go`. It seems that Ginkgo is prepending `api` to the front because the API package is the one I ran, but the compilation failure was in the `database` package, which `api` depends on.

**Comment by onsi** [comment]
ok I'll take a look
