### ISSUE TITLE
AfterEach failure should indicate which test it's running after

### ISSUE THREAD

**Issue by zmb3** [onsi/ginkgo#380]
I'd like to enable a pattern where a mock is set up in a `BeforeEach()`, expectations are set in each `It()`, and an assertion that expectations were met is done in an `AfterEach()`.

While this works currently, if an `It` spec fails to meet expectations, the error occurs in the `AfterEach` and there's no verbiage to help indicate _which_ spec failed.

Would it be possible for failures in an `AfterEach` to spit this out?  Something like: 

`--- FAIL: TestFoo (0.00s) - Running after spec bar`

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.  Ginkgo's reporter does emit information about the location of the test that failed - even if the failure is in an `AfterEach`.
I'm going to close this for now, but feel free to reopen it if you'd like.
