### ISSUE TITLE
Flakey / leaky integration tests

### ISSUE THREAD

**Issue by hoegaarden** [onsi/ginkgo#394]
When we run the tests as described in the contribution guide (`ginkgo -r -p`), we see that the test for the coverage integration tests are very flakey.
We think that is because of race condition in `integration/coverage_test.go` when tests run in parallel -- in `AfterEach` a fixtures directory is being removed while other tests, depending on that, are potentially running.

The error we see quite often is (similar to):
```
• Failure [3.115 seconds]
Coverage Specs [It] runs coverage analysis in series and in parallel
/Users/pivotal/go/src/github.com/onsi/ginkgo/integration/coverage_test.go:18

  Expected error:
      <*exec.ExitError | 0xc4200ec880>: {
          ProcessState: {
              pid: 86028,
              status: 256,
              rusage: {
                  Utime: {
                      Sec: 0,
                      Usec: 25735,
                      Pad_cgo_0: [128, 255, 255, 255],
                  },
                  Stime: {
                      Sec: 0,
                      Usec: 36515,
                      Pad_cgo_0: [0, 0, 0, 0],
                  },
                  Maxrss: 9101312,
                  Ixrss: 0,
                  Idrss: 0,
                  Isrss: 0,
                  Minflt: 11850,
                  Majflt: 3,
                  Nswap: 0,
                  Inblock: 0,
                  Oublock: 0,
                  Msgsnd: 0,
                  Msgrcv: 0,
                  Nsignals: 3,
                  Nvcsw: 374,
                  Nivcsw: 735,
              },
          },
          Stderr: nil,
      }
      exit status 1
  not to have occurred

  /Users/pivotal/go/src/github.com/onsi/ginkgo/integration/coverage_test.go:32
------------------------------
```

The revision we have seen this in is 7a241e9c6c7fb89adf3965bd763b7369b88a51eb, we believe that this problem already exists longer, but we didn't triage it.

How to reproduce:
- run `ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace -p -untilItFails -focus 'Coverage' integration/` in the root of the project
- See that the tests **fail** pretty fast (for us consistently on 1st or 2nd run currently)
- run `ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace -p -untilItFails integration/` (without focusing on the coverage tests)
- See that the tests **fail** after a couple of runs, not as consistent as the one above
- run `ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace -untilItFails -focus 'Coverage' integration/` (without `-p` but focusing on the coverage tests)
- See that the tests **succeed** consistently

**Comment by williammartin** [comment]
Thanks for the investigation, would gladly accept a PR to fix this so we can also do #395

**Comment by alamages** [comment]
@hoegaarden indeed the error is due to a race condition in `integration/coverage_test.go`.

The coverage tests generate/delete files to/from the same fixtures directory thus they interfere with each other. 

For example as pointed, the above error is thrown from the go cover tool failing to parse the generated coverprofile file `./_fixtures/coverage_fixture/coverage_fixture.coverprofile`

A solution to this, as similarly done in other integration tests, would be each test to copy the coverage fixtures to a temp directory and run them from there. Unfortunately in the coverage tests case this is not very straightforward.

Ginkgo is using go cover tool to generate coverage profiles. This tool achieves this by rewriting  the target package's source code before compilation to add instrumentation. 

The target package for coverage tests in ginkgo is: `github.com/onsi/ginkgo/integration/_fixtures/coverage_fixture`

In order to successfully run the cover tool the fixtures package must be in GOPATH-like directory so it can be imported. And since the fixtures' source code is going to be re-written we need to make sure that the fixture tests are importing the correct re-written package. 

For example let's take the case where we run:
```
ginkgo -cover /tmp/anothergopath/src/coverage_fixture
# the directory looks likes like:
# ├── coverage.go
# ├── coverage_fixture_suite_test.go
# ├── coverage_fixture_test.go
# └── external_coverage_fixture
#     └── external_coverage.go
```
When we copy fixtures into the tmp dir the `coverage_fixture_test.go` still imports the coverage_fixture package from: 
```
package coverage_fixture_test

import (
	. "github.com/onsi/ginkgo/integration/_fixtures/coverage_fixture"
...
)
```
The go cover tool will re-write the `/tmp/anothergopath/src/coverage_fixture` code before compilation but since the fixture tests still mention the package `github.com/onsi/ginkgo/integration/_fixtures/coverage_fixture` the generated profile file will report 0% coverage. From the cover tool's perspective the instrumented/re-written code is never invoked.

To successfully run the coverage from the temp dir the `coverage_fixture_test.go` imports should look like:
```
import (
	. "coverage_fixture"
...
)
```

And the GOPATH should include the temp dir, something like:
```
GOPATH=/home/user/go:/tmp/anothergopath
```

So, each test should:
- Copy the fixtures into a GOPATH-like temp directory
- The coverage_fixture packagge imports in the `coverage_fixture_test.go` must be replaced with the fixture package name from the temp directory
- The temp directory should be added in the GOPATH
- Every command run in the tests should get the updated/modified GOPATH in its environment

I have created a [fix-coverage-tests branch on github/alamages](https://github.com/alamages/ginkgo/tree/fix-coverage-tests) to test this. It's still work in progress. Following the above path I have managed to run 4 coverage tests in parallel without errors. With the above additions the test code will need refactoring to remain clean and readable.

@williammartin thoughts?

**Comment by alamages** [comment]
On the other side the above approach might not even be necessary if we group the tests in a way which they don't interfere which will be way simpler and cleaner. I will investigate.

**Comment by onsi** [comment]
This is fixed on v2 now
