### ISSUE TITLE
Memory leak detection

### ISSUE THREAD

**Issue by arthurgustin** [onsi/ginkgo#412]
In my team we have a mature code-base, and some of our services have memory leak. We are currently investigating on those issues, and me found this library: github.com/fortytw2/leaktest that can be integrated in golang standard tests to help detect thos leaks.
However we use ginkgo for our tests and we are glad to do so, but we cannot use this library.

Any plans to give access to the underlying `t *testing.T` I (don't even know if it's possible, didn't dig in the ginkgo code)  of to add this functionnality ?

**Comment by onsi** [comment]
This is cool!  So it looks like `leaktest` takes `t` via an `ErrorReporter` interface which `GinkgoT()` should satisfy.

Try adding this at the very top level of your Ginkgo suite to enable leak checking for _all_ your tests (warning: pseudocode - might not compile! but should give you the right idea):

```golang

var leakChecker func()

var _ = BeforeEach(func() {
    leakChecker = leaktest.Check(GinkgoT())
})

var _ = AfterEach(func() {
    leakChecker()
})
```

I'm _pretty_ confident that Ginkgo should pollute your goroutine profile and so you shouldn't get any false negatives due to the test-runner but I'm not positive.

I noticed that LeakTest doesn't support Goalng parallel tests.  What's cool is that this _will_ work with Ginkgo's parallelization scheme since Ginkgo uses multiple processes for parallelization!

**Comment by onsi** [comment]
@arthurgustin lemme know if this works.  If it does it might be worth adding to the Ginkgo docs.

**Comment by arthurgustin** [comment]
Hi @onsi, thank you for your great answer.
I just copied/pasted your code and it just worked, good job !

```
        var leakChecker func()

	var _ = BeforeEach(func() {
		leakChecker = leaktest.Check(GinkgoT())
	})

	var _ = AfterEach(func() {
		leakChecker()
	})

        Context("leak function", func() {
		It("should fail because it leaks", func() {
			go func() {
				for {
					time.Sleep(time.Second)
				}
			}()
		})
	})
```

Output:
```
• Failure in Spec Teardown (AfterEach) [5.002 seconds]
CSW
/home/agustin/gocode/src/airbus/datastore/catalog-api-csw/api/csw_test.go:28
  leak function [AfterEach]
  /home/agustin/gocode/src/airbus/datastore/catalog-api-csw/api/csw_test.go:282
    should fail because it leaks
    /home/agustin/gocode/src/airbus/datastore/catalog-api-csw/api/csw_test.go:283

    leaktest: timed out checking goroutines

    /home/agustin/gocode/src/airbus/datastore/catalog-api-csw/api/csw_test.go:37
```

**Comment by arthurgustin** [comment]
@onsi Unfortunately it did not find our issues because we encounter the leak only on load-test, but it is not in the scope of this issue.
Thank you

**Comment by arthurgustin** [comment]
Hi @onsi, thank you for your fast answer !
Your code compile, but I don't get the expected behavior of the leaktest library, it goes on timeout:
`leaktest: timed out checking goroutines`. Any ideas ?

**Comment by williammartin** [comment]
Seems like expected behaviour, when I run the example on `leaktest` repo:

```
func TestPool(t *testing.T) {
	defer leaktest.Check(t)()

	go func() {
		for {
			time.Sleep(time.Second)
		}
	}()
}
```

via `go test`, I get:

```
--- FAIL: TestPool (5.03s)
        leaktest.go:126: leaktest: timed out checking goroutines
        leaktest.go:144: leaktest: leaked goroutine: goroutine 7 [sleep]:
                time.Sleep(0x3b9aca00)
                        /usr/local/Cellar/go/1.9.2/libexec/src/runtime/time.go:65 +0x130
                github.com/williammartin/goleaktest_test.TestPool.func1()
                        /Users/pivotal/go/src/github.com/williammartin/goleaktest/goleaktest_test.go:18 +0x2a
                created by github.com/williammartin/goleaktest_test.TestPool
                        /Users/pivotal/go/src/github.com/williammartin/goleaktest/goleaktest_test.go:16 +0x69
```

So it seems like we are just missing some useful output. 🤔

**Comment by williammartin** [comment]
Ah, it's because the ginkgo `testingproxy` fails the test (https://github.com/onsi/ginkgo/blob/master/internal/testingtproxy/testing_t_proxy.go#L29) on the first call to `t.Errorf()` here: https://github.com/fortytw2/leaktest/blob/master/leaktest.go#L126 and never makes it to https://github.com/fortytw2/leaktest/blob/master/leaktest.go#L144 where the list of leaked goroutines are printed. 

So it seems you are leaking goroutines in your test, but Ginkgo doesn't print what is leaking. 

@onsi Any thoughts on this one?

**Comment by fortytw2** [comment]
:thinking: having just stumbled upon this issue, thought I might chime in about how leaktest is expected to work - after the function returned by `leaktest.Check(t)` is called (the `defer x()` bit), it loops to see if the list of goroutines matches what it was before the test started, so it's not super picky about things that may clean up 100ms or so after the test ends. 

Perhaps the `t.Errorf` here https://github.com/fortytw2/leaktest/blob/master/leaktest.go#L147 should instead finish with a `t.Fatalf` to ensure that it actually finishes the test - this may be what's funky with the `gingoT` here

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'm planning on adding leak detection as a native Ginkgo feature in v2.

I'm going to close this for now, but feel free to reopen it if you'd like.
