### ISSUE TITLE
How to run async benchmark tests

### ISSUE THREAD

**Issue by momchil-sap** [onsi/ginkgo#419]
Hi,

According to the documentation of Ginkgo, it should be possible to run asynchronous benchmark tests: https://onsi.github.io/ginkgo/#asynchronous-tests

> The body functions in all non-container blocks (Its, BeforeEaches, AfterEaches, JustBeforeEaches, and Benchmarks) can take an optional done Done argument

Unlike `It` blocks, `Measure` blocks also require a `Benchmarker` argument to be specified, hence it's not clear from the documentation where the `Done` argument should be placed, and there don't seem to be any examples

I tried both options:

```go
Measure("check", func(done Done, b Benchmarker) {
  // async stuff
}, 1)
```

```go
Measure("check", func(b Benchmarker, done Done) {
  // async stuff
}, 1)
```

Neither worked for me and I received the following error:

```bash
reflect: Call with too few input arguments
```

The exception seems to occur in `github.com/onsi/ginkgo/internal/leafnodes.NewMeasureNode.func1()`

My use case is that I want to do a performance test of a solution and would like to have multiple client calls run in parallel, hence they are executed in go routines.

Any idea what I am doing wrong? Have I misread / overlooked the documentation?

**Comment by williammartin** [comment]
@momchil-sap Yep, I get the same thing and definitely see something funny going on here.

There is a switch statement which determines whether the test should be sync or async (https://github.com/onsi/ginkgo/blob/master/internal/leafnodes/runner.go#L38-L55) depending on the number of args given (e.g. `func(done Done) = 1`)

In the `It(` case this works fine because the test function is passed straight through (https://github.com/onsi/ginkgo/blob/master/internal/leafnodes/it_node.go#L19)

However in the `Measure(` case, the test function is wrapped up (https://github.com/onsi/ginkgo/blob/master/internal/leafnodes/measure_node.go#L22-L27) in a 0 arg function. Then when `reflect.ValueOf` is called in the wrapped function (https://github.com/onsi/ginkgo/blob/master/internal/leafnodes/runner.go#L110) it explodes because the test function is expecting a `Benchmarker` and a `Done`.

I'm not sure whether this is a problem with the docs or a bug right now, but I'm not surprised it's not working for you. Sorry for the confusion.

@onsi What do you think? Bug or fix the docs?

**Comment by williammartin** [comment]
I pushed a commit over in my fork with a potential hacky solution (https://github.com/williammartin/ginkgo/commit/9726ceae9cec233014f9257838bb2a8d0d7532ef). 

| don't like the code, and I think we'd prefer removing async test altogether, but I'm interested if it works like you expect. I was able to write a test like:

**Comment by momchil-sap** [comment]
@williammartin , I checked your solution and it seems to work. 

However, if you omit the `Done` argument, it prints an address to stdout. I suspect you weren't going for a productive solution with that commit, but just something to keep in mind.

On a side note, you said you wanted to remove async testing. What did you have in mind? (just curious)

**Comment by williammartin** [comment]
@momchil-sap Sorry for the super late reply. The async tests are a bit sketchy, complicate Ginkgo and often lead to unintended side effects such as go routines failing unrelated tests in the future. We mostly recommend that people use the asynchronous assertions in Gomega now: https://onsi.github.io/gomega/#making-asynchronous-assertions

How are you feeling about this piece of work now, still something you'd find value in?

**Comment by momchil-sap** [comment]
@williammartin , what you have described makes sense.

In the meantime, I had changed my code to propagate the error back from all go-routines to the calling `It`. There I could use `Eventually` or `Expect` (depending on the test flow) to verify that no error had occured. 
I guess it resulted in a bit more complicated test code (since I needed to aggregate and synchronize errors from multiple go-routines (fan-in)) but resulted in a more explicit test.

I am closing this issue now. Thanks for the help!
