### ISSUE TITLE
Clarify docs about bootstrap

### ISSUE THREAD

**Issue by kswope** [onsi/ginkgo#442]
The docs are very clear, but I ran into one problem that stopped me for a while.

Looks like bootstrap must be run in every package, but "package" sorta has two meanings in golang, the "project" (technically the main package), and its included package dependencies.  So I was only running bootstrap at the top level, running generate in the subdirectory packages, using the recursive switch, and was baffled longer than I'd want to admit.

I think maybe the header "Bootstrapping a Suite" is what led me down the wrong path.  In my experience a project never has multiple test "suites", so I went immediately from "a suite", to go "main package", to off the rails.

**Comment by kirederik** [comment]
Hey @kswope,

That makes sense. Do you mind submitting a PR for that? The docs live here: https://github.com/onsi/ginkgo/tree/gh-pages

Thanks!

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.  This is helpful feedback on the docs, I'm planning on revising them for the upcoming v2  release and will make a note to look at this.

I'm going to close this for now, but feel free to reopen it if you'd like.
