### ISSUE TITLE
Flaky asynchronous test fails with wrong spec state

### ISSUE THREAD

**Issue by williammartin** [onsi/ginkgo#465]
Occasionally when I run the ginkgo tests I see the following failure:

```
• Failure [0.030 seconds]
Shared RunnableNode behavior JustBeforeEach Nodes asynchronous functions when the function times out [It] should return the timeout 
/tmp/build/a94a8fe5/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/shared_runner_test.go:216

  Expected
      <types.SpecState>: 5
  to equal
      <types.SpecState>: 6

  /tmp/build/a94a8fe5/gopath/src/github.com/onsi/ginkgo/internal/leafnodes/shared_runner_test.go:220

  Full Stack Trace
  	/tmp/build/a94a8fe5/gopath/src/github.com/onsi/gomega/internal/assertion/assertion.go:69 +0x25b
  github.com/onsi/gomega/internal/assertion.(*Assertion).Should(0xc42041e5c0, 0xb0dc40, 0xc4203504e0, 0x0, 0x0, 0x0, 0xc42041e5c0)
  	/tmp/build/a94a8fe5/gopath/src/github.com/onsi/gomega/internal/assertion/assertion.go:27 +0xd0
  github.com/onsi/ginkgo/internal/leafnodes_test.AsynchronousSharedRunnerBehaviors.func2.5.2()
  	/usr/local/go/src/testing/testing.go:777 +0x16e
  created by testing.(*T).Run
  	/usr/local/go/src/testing/testing.go:824 +0x565
```

**Comment by nodo** [comment]
@williammartin  I am not sure I have understood your point. Where would you put the sleep exactly?

A possible the root cause (maybe different from the one above) is the too narrow difference in time between the timeout (set to 10ms) and the sleep in the async func (set to 20ms)

Suppose that there is a sleep long enough before the `select` statement [here](https://github.com/onsi/ginkgo/blob/master/internal/leafnodes/runner.go#L90) (e.g. 50ms) . In that case, the timeout does not occur (rightfully), because the whole `runAsync` function is taking too long and the test panics. If this is the problem we could just add a bit of delay [here](https://github.com/onsi/ginkgo/blob/master/internal/leafnodes/shared_runner_test.go#L209).

However, is it possible that this sleep would happen? 🤔

**Comment by nodo** [comment]
@williammartin any thoughts on the comment above?

**Comment by williammartin** [comment]
Yes but I thought we could discuss when you're back. Not the easiest to describe racy behaviour over GitHub.
