### ISSUE TITLE
RFC: Add a GoTestReporter

### ISSUE THREAD

**Issue by msabramo** [onsi/ginkgo#472]
Was playing with the goconvey web UI and noticed it expects `go test` style output and gets confused by Ginkgo tests. 

I wonder if it would make sense to write a `GoTestReporter` that emits `RUN: <test name>`, `— PASS:`, etc. for each ginkgo test case (not just for the whole suite) ?

**Comment by williammartin** [comment]
This sounds like a good idea to me, there must be a bunch of tools out there that try to parse Go test output.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.  V2, which is under active development, will introduce a new JSON format.  I imagine that would be an ideal starting point for building tooling on top of.

I'm going to close this for now, but feel free to reopen it if you'd like.
