### ISSUE TITLE
Why `It` is not allowed in `BeforeSuit` or `AfterSuit`

### ISSUE THREAD

**Issue by a4abhishek** [onsi/ginkgo#475]
I am using GinkGo for Integration testing. My code is below:
```
package integrationtest

import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestNDM(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Integration Test Suit")
}

var _ = BeforeSuite(func() {
	It("Waits till namespace is ready", func() {})
	It("prepares configuration and Applies the same", func() {})
	It("waits till node-disk-manager is ready", func() {})
})

var _ = AfterSuite(func() {
	It("Delete minikube if it is running", func() {})
	It("Removes residue containers", func() {})
	It("Removes remaining residue files", func() {})
})

var _ = Describe("Integration Test", func() {})
```
When I run this test I am getting error:
```
abhishek@genesis:~$ /usr/local/go/bin/go test -v -timeout 30m github.com/openebs/node-disk-manager/integration_test -run ^TestNDM$
=== RUN   TestNDM
Running Suite: Integration Test Suit
====================================
Random Seed: 1527244493
Will run 0 of 0 specs

Failure [0.000 seconds]
[BeforeSuite] BeforeSuite 
/home/abhishek/GoWorkspace/src/github.com/openebs/node-disk-manager/integration_test/ginkgo_integration_test.go:15

  You may only call It from within a Describe, Context or When

  /home/abhishek/GoWorkspace/src/github.com/openebs/node-disk-manager/integration_test/ginkgo_integration_test.go:16
------------------------------
Failure [0.000 seconds]
[AfterSuite] AfterSuite 
/home/abhishek/GoWorkspace/src/github.com/openebs/node-disk-manager/integration_test/ginkgo_integration_test.go:21

  You may only call It from within a Describe, Context or When

  /home/abhishek/GoWorkspace/src/github.com/openebs/node-disk-manager/integration_test/ginkgo_integration_test.go:22
------------------------------

Ran 0 of 0 Specs in 0.001 seconds
FAIL! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped
--- FAIL: TestNDM (0.00s)
FAIL
exit status 1
FAIL	github.com/openebs/node-disk-manager/integration_test	0.044s
```
Which is because GinkGo does not support `It` in `BeforeSuit` or `AfterSuit`.
So, I Chaged the code to this:
```
package integrationtest

import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestNDM(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Integration Test Suit")
}

var _ = BeforeSuite(func() {
	Describe("Before Suit", func() {
		It("Waits till namespace is ready", func() {})
		It("prepares configuration and Applies the same", func() {})
		It("waits till node-disk-manager is ready", func() {})
	})
})

var _ = AfterSuite(func() {
	Describe("After Suit", func() {
		It("Delete minikube if it is running", func() {})
		It("Removes residue containers", func() {})
		It("Removes remaining residue files", func() {})
	})
})

var _ = Describe("Integration Test", func() {})
```
Still geting error:
```
abhishek@genesis:~$ /usr/local/go/bin/go test -v -timeout 30m github.com/openebs/node-disk-manager/integration_test -run ^TestNDM$
=== RUN   TestNDM
Running Suite: Integration Test Suit
====================================
Random Seed: 1527244641
Will run 0 of 0 specs

Failure [0.001 seconds]
[BeforeSuite] BeforeSuite 
/home/abhishek/GoWorkspace/src/github.com/openebs/node-disk-manager/integration_test/ginkgo_integration_test.go:15

  You may only call It from within a Describe, Context or When

  /home/abhishek/GoWorkspace/src/github.com/openebs/node-disk-manager/integration_test/ginkgo_integration_test.go:17
------------------------------
Failure [0.001 seconds]
[AfterSuite] AfterSuite 
/home/abhishek/GoWorkspace/src/github.com/openebs/node-disk-manager/integration_test/ginkgo_integration_test.go:23

  You may only call It from within a Describe, Context or When

  /home/abhishek/GoWorkspace/src/github.com/openebs/node-disk-manager/integration_test/ginkgo_integration_test.go:25
------------------------------

Ran 0 of 0 Specs in 0.003 seconds
FAIL! -- 0 Passed | 0 Failed | 0 Pending | 0 Skipped
--- FAIL: TestNDM (0.00s)
FAIL
exit status 1
FAIL	github.com/openebs/node-disk-manager/integration_test	0.044s
```
Now the question is Why can we not do this at all. This makes code more readable, which is the whole purpose of having `It` or `GinkGo` or `BDD`.

I might not know the best practices and standards, as this is my first experience with GinkGo or even Testing. So I shall appreciate if someone points out that too.

You can find *filled template* [here](https://github.com/a4abhishek/node-disk-manager/blob/integration-test-ginkgo/integration_test/ginkgo_integration_test.go).

**Comment by williammartin** [comment]
Hi @a4abhishek thanks for your detailed writeup and examples. I think you're just missing a slight nuance in testing in a BDD style but otherwise really close! You really want your `It` blocks to represent the things specifically under test in this suite e.g. when I look at https://github.com/a4abhishek/node-disk-manager/blob/d7d92a58d4248f9eda99b4f0b11acd44dbe60a8e/integration_test/ginkgo_integration_test.go, if you care about `WaitTillDefaultNSisReady` then that should be tested as a separate unit.

When I read this:

```
var _ = BeforeSuite(func() {
	It("Waits till namespace is ready", func() {})
	It("prepares configuration and Applies the same", func() {})
	It("waits till node-disk-manager is ready", func() {})
})
```

It is not clear to me what `It(` refers to. _What_ waits till the namespace is ready? _What_ prepares configuration and applies the same"? _What_ waits till the node-disk-manager is ready?

If there were a thing called `Config` which had a `Prepare()` and `Apply()` method I would consider doing something like:

```
Describe("Config", func() {
    Describe("Prepare", func() {
        It("prepares as yaml", func() { ... })
    })

    Describe("Apply", func() {
        It("saves the yaml to disk", func() { ... })
     })
})
```

Ginkgo is opinionated in the BDD style, and will not allow you to run specs (`It` blocks) in `Before` or `After` blocks because they should represent any setup or teardown you need to do to prepare your environment _for the thing under test_.

Here's a random example of something I was messing about with in a side project: https://github.com/williammartin/nsjam/blob/master/marley/list_namespaces_test.go

You can see that the _thing_ under test is the `list-namespaces` command. Before any `It` block is run, we do any common setup, and then we can assert for things we care about for this suite. We should not be _testing_ that utility functions have a certain behaviour _in this suite_, because _this suite_ is for `list-namespaces`. E.g. perhaps you would want:

```
Describe("Logging", func() {})
```

and maybe:

```
Describe("Disk Management", func() {})
```

I hope this makes some kind of sense to you :)

**Comment by a4abhishek** [comment]
Thanks @williammartin for the great reply and also for replying this fast. I am trying to grasp it completely, but I understand one thing for sure that we should not use `It` for the things which result doesn't matter to us.
And sorry for my late reply.

**Comment by williammartin** [comment]
"Also, you might want to improve the error message You may only call It from within a Describe, Context or When." -> Yep this might be a bit confusing. Have opened #485 and going to close this issue now. Thanks!
