### ISSUE TITLE
"You may only call It from within a Describe, Context or When" isn't always clear

### ISSUE THREAD

**Issue by williammartin** [onsi/ginkgo#485]
See: https://github.com/onsi/ginkgo/issues/475

**Comment by bboreham** [comment]
Another way this can happen is if you call `RunSpecs()` twice in the same directory. https://github.com/containernetworking/plugins/pull/529

**Comment by stefanKnott** [comment]
i am getting this error when running table driven tests when setting -count flag in go test as such:

go test -count 100 ./...

any update here?

**Comment by onsi** [comment]
@stefanKnott I _think_ `-count` was added a while after Ginkgo was first written.  It looks like the go test runner is rerunning the `Test` function in which `RunSpecs` is registered - but Ginkgo is designed to only have `RunSpecs` called once.  You're only seeing it in 1.14.1 because 1.14 is where Ginkgo started to be more verbose about that requirement (it's always been the case).  I'm going to improve the user feedback when this scenario is hit in general (i.e. calling `RunSpecs` more than once) and specifically when the user invokes `go test` with `-count`.

If your goal is to rerun the tests repeatedly to suss out flakes I recommend using `ginkgo --untilItFails`

**Comment by onsi** [comment]
These error messages will be much cleaner in v2.
