### ISSUE TITLE
There is no way(flag) to hide showing line numbers for passing tests

### ISSUE THREAD

**Issue by syamgk** [onsi/ginkgo#534]
There should be a way to printing line numbers to the stdout and just the Spec names to the stdout stream

**Comment by williammartin** [comment]
Can you provide some examples for what you would like to see, compared to current output? I'm not sure I understand.

**Comment by syamgk** [comment]
Hi @williammartin , we are using this for writing end to end tests for [Odo project](https://github.com/redhat-developer/odo). 
you can find the end2end test logs [here](https://travis-ci.org/redhat-developer/odo/jobs/451279473#L724) 
and I am looking for a way to only log the specs which are running and commands.
And the line numbers and expected output should only be shown when a test fails

Logs right now:
```
------------------------------
odoCmpE2e odo component creation 
  should be in application description
  /home/travis/gopath/src/github.com/redhat-developer/odo/tests/e2e/cmp_test.go:71
Running command: odo describe
Component cmp-git of type nodejs with source in https://github.com/openshift/nodejs-ex
•
------------------------------
```

Expecting the logs to be like:
```
------------------------------
odoCmpE2e odo component creation 
  should be in application description
Running command: odo describe
•
------------------------------
```
I've tried modifying the tests a bit on my pr to odo here https://github.com/redhat-developer/odo/pull/925
but not finding a way to strip the line numbers in the cases of successful tests.

**Comment by williammartin** [comment]
Thanks! I understand now. Can you tell me a little more about the reason you don't want this printed?

**Comment by amitkrout** [comment]
@williammartin @syamgk Or probably add some flag so that these verbose can be mute and unmute as per user choice.

**Comment by wingyplus** [comment]
Or just hide it by default and print it when test got failed.

**Comment by williammartin** [comment]
I think I'm a little confused again by this request (which is definitely my fault for letting it get stale, sorry). 

If you are experiencing this as an issue can you drop the command you're running in here. The reason I ask is because I only recall line numbers being printed if:
 - The test fails
 - You have verbose output (`-v`) enabled
 - Your test exceeds the slow threshold

Thanks all.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

Agreed with @williammartin that this really only happens with `-v` in which case you're asking for verbose output and so will be getting the file:line annotations.

I'm going to close this for now, but feel free to reopen it if you'd like.
