### ISSUE TITLE
when use `go test` instead of `ginkgo`, its output is still not change.

### ISSUE THREAD

**Issue by magicsong** [onsi/ginkgo#536]
There is only one line in output like native `go test`:
```
ok      github.com/magicsong/******/generate     0.033s
```
how can i get the ginkgo-style output use `go test`. 
BTW, the command i use is `go test path/to/package`. When i `cd` in the package directory just use `go test`, it works. Why?

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

`go test` has opinions about how how to display output and does it differently in different contexts (e.g. multiple packages vs one).  I recommend using `ginkgo` instead of `go test`.

I'm going to close this for now, but feel free to reopen it if you'd like.
