### ISSUE TITLE
How to run test when start ginkgo watch start? (change) Please reply..

### ISSUE THREAD

**Issue by kkokey** [onsi/ginkgo#538]
I would like run test with ginkgo watch start.
But not found any option about that thing.

Do you have plan? or any idea?
Important thing is with start.

ginkgo is always only start.
I have to change some code when I want start test.

**Comment by williammartin** [comment]
Hi @kkokey, is there some reason you don't want to just use `ginkgo` by itself to run your tests?

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

`ginkgo watch` will run your test if there's only one.  Otherwise it will wait until a test/package has been changed and just run that test/package.

I'm going to close this for now, but feel free to reopen it if you'd like.
