### ISSUE TITLE
Feature request: Allow AfterEach functions to tell the summary.State of the current test, not just if it is Failed.

### ISSUE THREAD

**Issue by cquon** [onsi/ginkgo#541]
I have a use case where I'd like to see the test status, particularly if it is Skipped, not just Failed.  Looking at this closed issue https://github.com/onsi/ginkgo/issues/163 and the code, it looks like only Failure is exposed.  I can open a PR for this issue.

**Comment by onsi** [comment]
This ill be fixed in v2

**Comment by onsi** [comment]
A beta for Ginkgo V2 that fixes this issue was just released.  `CurrentSpecReport()` can now be called from any Ginkgo node and includes up-to-date information about the current running test.  More importantly, there's a new `ReportAfterEach()` that is guaranteed to be called even if the spec is skipped (whether programmatically or via Ginkgo's filtering mechanisms).

[Please try out the beta](https://github.com/onsi/ginkgo/issues/809)!
