### ISSUE TITLE
Display `By` in the error trace

### ISSUE THREAD

**Issue by joaopapereira** [onsi/ginkgo#547]
I was wondering if this feature would be of any interest.

At this time when `By` is added into a test it writes it only outputs the `STEP` information in the log. But when it fails the log does not inform about the last `By` that we defined.

An example would be:
```go
var _ = Describe("Some suite", func() {
	Describe("in a particular case", func() {
		It("saves the world", func() {
                     By("Doing something awesome")
                     Expect(1).ToBe(Equal(2))
                 })
        })
})
```
Output:
```
• Failure [1036.886 seconds]
in a particular case
/some_file.go:33
  saves the world [It]
  /some_file.go:50

Expected
      <int>: 1
  to equal
      <int>: 2
```

I do believe that a output that would look like the following would help pinpoint the place where the error happened in a easier way and would also make the stack easier to interpret:
```
• Failure [1036.886 seconds]
in a particular case
/some_file.go:33
  saves the world [It]
  /some_file.go:50
    Doing something awesome [By]
    /some_file.go:53

Expected
      <int>: 1
  to equal
      <int>: 2
```

When multiple `By` are present it should only save the latest.

Do y'll think this is a nice feature to be added?

**Comment by williammartin** [comment]
I can definitely see why this would be useful. As someone who is fairly anti `By()` I suppose I would encourage writing more compact tests that this isn't required, but I can totally understand how this would be useful if someone were using `By()`.

Would you be willing to attempt a PR?

**Comment by dlipovetsky** [comment]
+1 for this feature.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

`By` is pretty hacky and I'm working, instead, on resolving some of the underlying root causes that led to its creation (lack of `BeforeAll` leading to monolithic `It`s, for example).  It would be challenging to integrate the `By` file:line into Ginkgo's output cleanly at this point so I'd like to avoid doing it.

I'm going to close this for now, but feel free to reopen it if you'd like.
