### ISSUE TITLE
Assertions of Measure() average result.

### ISSUE THREAD

**Issue by Julio-Guerra** [onsi/ginkgo#551]
Hello,

I couldn't use `Measure()` to make assertions on time measurements, which are sensitive to the scheduling, because it only allows to run assertions on a single sample. For example:

```
Measure("...", func (b Benchmarker) {
  slower := b.Time("...", func () {
    ...
  })
  faster := b.Time("...", func () {
    ...
  })
  Expect(slower).Should(BeNumerically("<", faster))
}, 1000)
```

The scheduling impacts the time measurements, sometimes making the assertion false. Being able to run the assertion of the average value would allow to get rid of this (they should be on average the same for both).

For now, I had to rewrite it to:

```
Measure("...", func (b Benchmarker) {
  var slowerAvg, fasterAvg int
  for n := 1; n <= 1000; n++ {
    slower := b.Time("...", func () {
      ...
    })
    slowerAvg = ...
    faster := b.Time("...", func () {
      ...
    })
    fasterAvg = ...
  }
  Expect(slowerAvg).Should(BeNumerically("<", fasterAvg))
}, 1)
```

Do you have better ways of running assertions on time measurements, which are sensitive to the scheduler?

If not, I think `Measure()` could give access to the stats it accumulates (fastest, average and slowest). Using for example an extra function argument to run the assertion based on the end results.

Thank you

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

I'm planning on removing `Measure` from Ginkgo and, instead, introducing benchmarking support as a separate Gomega library.  This will make it possible to make more granular measurements and then make assertions on those measurements within a given test.  As currently constructed `Measure` replaces `It` which is semantically unnecessary and limiting.

I'm going to close this for now, but feel free to reopen it if you'd like.
