### ISSUE TITLE
Integrating ginkgo with testrail api to add result test to Test Rail

### ISSUE THREAD

**Issue by cuongld2** [onsi/ginkgo#569]
Hi there,
I am integrating ginkgo with TestRail API.
I would like to do the trick if the the test is failed because of fail assertion in It blocks, a value will be got and then I can parse value to the test rail API to update the test result to test rail.

But the problem is, in It block, when something failed in the assertion, it will skip all the below code.
How can I achieve this?
Thanks so much.

`			It("Expect all info are updated", func() {
				 messageVerify :=Expect(s.Message).To(Equal("Relation timeline can not update fre"))
				 codeVerify :=Expect(s.Code).To(Equal("20901"))
				 // If something failed, the below code will not be executed

				verifyTest = messageVerify &&codeVerify
				fmt.Println("Verify the test 1:", verifyTest)

				if verifyTest==true {
					newResult.StatusID = 1
				}
				if verifyTest!=true{
					newResult.StatusID = 5
				}

				// API for test Rail to add result
				createdResult, err := client.AddResultForCase(486,7962,newResult)
				if err!=nil{

					fmt.Println(err)

				}
				fmt.Println(createdResult.StatusID)

			})`

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

You can accomplish this using an `AfterEach` that looks at `CurrentGinkgoTestDescription()` to figure out if the test failed.  I'll be adding more details to `CurrentGinkgoTestDescription()` as part of the v2 work that is under active development.

I'm going to close this for now, but feel free to reopen it if you'd like.
