### ISSUE TITLE
Writer implementation - internal type reuse

### ISSUE THREAD

**Issue by mjudeikis** [onsi/ginkgo#572]
We have a use case, where we want to send all logs into external log aggregator for centralised search. With help of customer reporter these logs can be tagged/labelled based on the suit. The initial plan was to use `GinkoWriter`:
```
orgWriter = GinkoWriter
GinkoWriter = customerWriter 
```
And in the `customWriter` send logs into both writers (cloud and originalWriter).

This does not work, because code casts GinkoWriter to internal type and using any `io.Writer` gives an error.
```
panic: interface conversion: io.Writer is *io.PipeWriter, not *writer.Writer [recovered]
```
https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L215

Another way was to either implement `writer.Writer` interface or just pass custom `io.Writer` into `New` function:
https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L56

But because all `writer` implementation sits under `internal` path/type, we cant use this package:
```
/test/e2e/e2e_test.go:9:2: use of internal package 
```

Can we either remove casting and make sure GinkoWriter complies with `io.Writer` interface or expose the ability to initiate `GinkoWriter` ourselves? 
Like create function on `ginko_dsl.go`: 
```
func InitCustomWriter(outWriter io.Writer) {
       GinkoWriter = writer.New(outWriter)
}
```

Or I might be missing some other functionality, which can be used to achieve our goal?

**Comment by williammartin** [comment]
@blgm I know you were looking around the reporting domain when you were adding the `debug` flag, do you have any thoughts on this?

**Comment by williammartin** [comment]
From my perspective, it does seem like we should just provide a function that allow

**Comment by williammartin** [comment]
Misclick, sorry ^

**Comment by mjudeikis** [comment]
@williammartin @blgm I think this is the most simple approach and least intrusive at the moment. And when you have bigger refactor underway, just make sure this is added to the backlog. If we agree on function, will raise a PR

**Comment by williammartin** [comment]
It seems acceptable to me right now. I think as long as the `GinkgoWriter` is set before `RunSpecs` is called this should be fine. In practice this really means anywhere except a `BeforeSuite`, `BeforeEach` or `It` (and friends), and before `GinkgoT`.

I'm not sure that we can get way with not needing the `writer.Writer` interface because the tests make extensive use of that behaviour, but maybe what we could do is either make it non-internal. Not really any elegant solutions I can think of right now because of the global nature of the `GinkgoWriter`.

**Comment by mjudeikis** [comment]
cool. let me raise a PR and we can take it from there

**Comment by mjudeikis** [comment]
https://github.com/onsi/ginkgo/pull/573

**Comment by onsi** [comment]
Sorry, I'm working through the backlog of old Ginkgo issues and am just getting to this now.  I'm seeing a few different folks request the ability to attach a custom writer to GinkgoWriter.  I'll add that to the v2 backlog and make it possible to do something like `GinkgoWriter.TeeTo(...)`.

**Comment by mjudeikis** [comment]
@onsi  better later than never :)

**Comment by onsi** [comment]
lol - indeed!

**Comment by onsi** [comment]
A beta for Ginkgo V2 that fixes this issue was just released.  `GinkgoWriter` now provides `TeeTo`.

[Please try out the beta](https://github.com/onsi/ginkgo/issues/809)!

**Comment by AzureMarker** [comment]
For anyone like us who aren't planning on using v2 until it's ready, but need to send Ginkgo logs through another logger, here is a workaround:
```golang
type GinkgoWriterHack interface {
	AndRedirectTo(writer io.Writer)
}

// Example given using logrus logger
ginkgo.GinkgoWriter.(GinkgoWriterHack).AndRedirectTo(myLogger.Writer())
```

Disclaimer: this might stop working after any version bump since this deals with internal types.

`AndRedirectTo` is public, but in the internal `writer.Writer` type. So declaring an interface with the same function lets us cast `GinkgoWriter` and call the function.

`AndRedirectTo` in Ginkgo's source code:
https://github.com/onsi/ginkgo/blob/f43583d78dd771a06b6f0eb07b6627b6e7fa467d/internal/writer/writer.go#L35-L37
