### ISSUE TITLE
Coverage for external golang app started by gexec.Start

### ISSUE THREAD

**Issue by i-kwilk** [onsi/ginkgo#589]
How to measure a coverage for an app "A" started inside of my ginkgo test application by

cmd := exec.Command("./A")
gexec.Start(cmd, GinkgoWriter, GinkgoWriter)

When I compile my test app within -cover flag it doesn't show the coverage inside of "A" app for tests that definitley uses "A" app. I know that golang might treat "A" as a separate app, but can I somehow compile "A" app within some speciall flags and then run a coverage test application to fill in the coverage file?

**Comment by williammartin** [comment]
I don't believe that this is possible but if you find a way to do this I would be extremely interested!

**Comment by sznowicki** [comment]
I know it maybe be even impossible but it would be super awesome.

I use ginkgo with `gexec.Build` for my cli application smoke test which should give me near 100% coverage, but I cannot really analyse that at the moment or use coverage from that test for static PR analysis.

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

Go provides `-coverpkg` as a means to tell the go test runner to track the coverage of additional packages by a given test suite, but I don't think that will work if something other than `go test` compiles the binary in question.  I might be possible to use `go tool cover` to annotate the code of your binary with coverage information before compiling it but I've never tried it.

I'm going to close this for now, but feel free to reopen it if you'd like.
