### ISSUE TITLE
Add a feature to skip test in context level when runs test file on a specific platform

### ISSUE THREAD

**Issue by amitkrout** [onsi/ginkgo#615]
We run same test spec on both Linux and windows platform but there are certain scenario that should be disabled on certain platform like Windows. Now my question is ```How can i disable a Context("Description", func(){...})``` on certain platform like windows ?```. In ginkgo doc i could not find a proper solution to achieve it. 

Please refer me the doc If this feature has been implemented in ginkgo. 

I am using 
```
$ ginkgo version
Ginkgo Version 1.10.2
```

**Comment by blgm** [comment]
Hi @amitkrout, there is no specific feature for what you describe, but I think your requirement could be achieved in the following ways:

1) Split the tests into separate files so that you have (for example) a file for Windows, a file for Linux and a file with shared tests. You can then use standard Go features to include/exclude the files: https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool

2) You could conditionally call Ginkgo's `Skip()` directive, for instance:
```go
When("on Windows", func() {
  BeforeEach(func() {
    if runtime.GOOS == "windows" {
      Skip()
    }
  })
  ...
})
```

Does that help?

**Comment by amitkrout** [comment]
> Hi @amitkrout, there is no specific feature for what you describe, but I think your requirement could be achieved in the following ways:
> 
> 1. Split the tests into separate files so that you have (for example) a file for Windows, a file for Linux and a file with shared tests. You can then use standard Go features to include/exclude the files: https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool
> 2. You could conditionally call Ginkgo's `Skip()` directive, for instance:
> 
> ```go
> When("on Windows", func() {
>   BeforeEach(func() {
>     if runtime.GOOS != "windows" {
>       Skip()
>     }
>   })
>   ...
> })
> ```
> 
> Does that help?

@blgm Thanks, both the options are really helpful. Will choose one best fit for our requirement.
