### ISSUE TITLE
Duplicate go test execution

### ISSUE THREAD

**Issue by devigned** [onsi/ginkgo#618]
```
$ go version
go version go1.13.4 darwin/amd64
$ ginkgo version
Ginkgo Version 1.10.1
```

In my project's test code, we have a combination of both ginkgo tests as well regular old Golang tests.
```
ginkgo -mod=vendor -skipPackage test/e2e -failFast -r -v -p -stream .
``` 
When executing from the root of the project, I can see output from a test duplicated for the number of nodes executing the tests. For example, I run the test with a `fmt.Println("I was here!!!")` in a regular Golang test and I get the following output (where the ellipsis implies other test output).

```
[2] I was here!!!
...
[3] I was here!!!
...
[1] I was here!!!
...
[4] I was here!!!
```

Is the test actually getting executed on each node or is it just the output is duplicated? If the tests are getting executed by each node, am I doing it wrong or is this a bug?

**Comment by onsi** [comment]
I'm working through the backlog of old Ginkgo issues - apologies as this issue is probably stale now.

If the golang tests are in separate packages this shouldn't be happening and would be a bug.  If the golang tests are in the same package as the Ginkgo tests then, yes, I would expect to see them duplicated because of how Ginkgo runs parallel tests.  Broadly speaking I'd say that support for mixing Ginkgo and non-Ginkgo tests in the same package is limited.  I'll update the README/docs to clarify that as I make progress on v2.

I'm going to close this for now, but feel free to reopen it if you'd like.
