### ISSUE TITLE
Specs aren't identified in `go test . -json` output

### ISSUE THREAD

**Issue by jamesrom** [onsi/ginkgo#639]
Running `go test . -json` does not produce usable output when using Ginkgo. To be fully compatible with standard go tooling, producing test events that conform to the [test2json spec](https://golang.org/cmd/test2json/) would be necessary. 

In particular, populating the `Test` field with not just the name of the function that ran the specs, but the name of the specs in the form form "Suite/Context/Spec/Etc".

**Comment by ansd** [comment]
It looks like `go test . -json` always outputs the name of the Golang testing `TestXxx(t *testing.T)` function as the `Test` Field in the JSON output. For Ginkgo, it's the suite function's name which calls `RunSpecs`.

Maybe, it's worth to implement a streaming JSON reporter in Ginkgo which would conform with the test2json spec.
A streaming JSON reporter has already been suggested in https://github.com/onsi/ginkgo/pull/143#issuecomment-75393126.

**Comment by onsi** [comment]
I'm going to be implementing the ability to emit a json test report in V2.  I'll look into go test's output to see if it's a good fit but i expect i'll be producing a ginkgo specific format.

**Comment by onsi** [comment]
A beta for Ginkgo V2 was just released.   It supports emitting JSON-formatted reports though, as mentioned above, it's Ginkgo's own JSON format which includes a bunch of rich test information.

[Please try out the beta](https://github.com/onsi/ginkgo/issues/809)!

**Comment by stotz89** [comment]
Hello, 
I know there are already a couple of issues and some discussions related to that topic however I wanted to ask this question. Since v2 Ginkgo produces its own json format as an output of the test results.

We are using Sonarqube to report back test coverage and test reports and unfortunately, at least as far as I know, Sonar expects the test reports in the test2json format produced by `go test`: 

> Path to test execution reports generated by Go with '-json' key, available since go1.10 (e.g.: go test -json > test-report.out).

One the one hand we could only use `go test` to get the desired outputs for test reports & coverage however on the other hand the output Ginkgo produces is just much more detailed that we also would like to see (in our CI pipeline). Therefore, our mitigation currently is to execute both steps (`go test` & `ginkgo`) to have the best of both but as said, should only be a mitigation.

So, my questions would be: 
1. Someone else have already faced & solved this issue? Could a `ReportAfterSuite` convert the report back into the test2json format?
2. Would it be a feasible that Ginkgo can bring back the support for a test2json output format?
