### ISSUE TITLE
Proposal: Add gRPC/http based Reporter

### ISSUE THREAD

**Issue by zhouhaibing089** [onsi/ginkgo#702]
We use ginkgo to run tests, and from time to time, we'd like to report flaky tests automatically to jira or github. This isn't something common, I guess. 

We obviously can implement one as a library so whatever projects when needed can import the library and then setup ginkgo(via `RunSpecsWithDefaultAndCustomReporters`) properly. However, it only works with internal projects. To work with open source projects, there won't be a common reporter that fits for all forks.

Based on this consideration, I'm proposing a common interface which allows people to run their out-of-tree reporters. The advantage of it is full flexibility - When we fork an open source project, we only need to change parameters to enable customized reporter. The downside, I guess it will add few more round trips and might introduce unexpected latencies in tests.

It is something like a proxy which can redirect these [callbacks][1] into an external system via grpc calls. Such mechanism is pretty common for out-of-tree extensions as it looks like today.

I'd like to see how the community think about this approach, Thanks!

[1]: https://github.com/onsi/ginkgo/blob/master/reporters/reporter.go

**Comment by onsi** [comment]
I like this idea.  Believe it or not the functionality kind of [already exists](https://github.com/onsi/ginkgo/tree/master/internal/remote).  When running parallel nodes, the `ginkgo` CLI starts a [server](https://github.com/onsi/ginkgo/blob/master/internal/remote/server.go) then launches multiple test processes with the address of the server encoded in a `GINKGO_REMOTE_REPORTING_SERVER` environment variable.  Detecting that environment variable causes Ginkgo to use the [`ForwardingReporter`](https://github.com/onsi/ginkgo/blob/master/internal/remote/forwarding_reporter.go) instead of the default reporter.  This then communicates with the server over http via JSON.  It's not gRPC and, honestly, I'd as soon keep it JSON.

The `GINKGO_REMOTE_REPORTING_SERVER` is intended to point to a server that can orchestrate parallel nodes.  But it wouldn't be too much work to add support for a new environment variable that configures an additional `ForwardingReporter` to point to an arbitrary server.  One thing to note is that when running in parallel, the server will need to be responsible for collecting the test results from the various nodes and combining them.

**Comment by jpm86** [comment]
> When running parallel nodes, the `ginkgo` CLI starts a [server](https://github.com/onsi/ginkgo/blob/master/internal/remote/server.go) then launches multiple test processes with the address of the server encoded in a `GINKGO_REMOTE_REPORTING_SERVER` environment variable. Detecting that environment variable causes Ginkgo to use the [`ForwardingReporter`](https://github.com/onsi/ginkgo/blob/master/internal/remote/forwarding_reporter.go) instead of the default reporter.

I've only just started browsing the codebase, but I don't think that's been the case for a while. `GINKGO_REMOTE_REPORTING_SERVER` is only mentioned once in the entire code base--in the comments for `ForwardingReporter`. It looks like the current mechanism passed the sever address via the `<prefix>.parallel.streamHost` flag.

Also, unless I'm misreading things, it seems like one could pass `ginkgo.parallel.streamHost=<some.arbitrary.server>` as a passthrough to the test suites, and it should trigger forwarding. One could also pass the same server address to `ginkgo.parallel.syncHost` and handle the `/BeforeSuiteState`, `/RemoveAfterSuiteStateData`, `/counter`, and `/has-counter` endpoints, but since `RegisterAlive` is a direct method on `Server` and not an endpoint, there might be issues with implementation. In any case, I don't see any obvious reason the reporting endpoints *have* to be served by the same host as the sync endpoints, so it would probably be better not to pass anything explicitly to `ginko.parallel.syncHost` and let the builtin server handle those endpoints.

> P.S. This is off-topic, but the reason I dove into this part of the code is because I'm evaluating its usefulness for implementing a test explorer adapter for ginkgo in vscode.

**Comment by onsi** [comment]
quick update here - i'm planning on introducing a `--json-report=XXX.json` flag that will cause Ginkgo to emit a JSON-formatted report.  I'm hoping this will allow folks to build their custom reporting infrastructure on top of the JSON file format instead of the custom reporter interface (which I'm aiming to deprecate and remove).  Thoughts and comments welcome!
