### ISSUE TITLE
Downloaded source code 1.14.0 and then use "go build" to generate ginkgo binary file. But it runs with errors.

### ISSUE THREAD

**Issue by fhwsuper** [onsi/ginkgo#724]
root@secure-lasers-2:/software/ginkgo-1.14.0/bin# ./ginkgo -v
./ginkgo: line 1: syntax error near unexpected token `newline'
./ginkgo: line 1: `!<arch>'

**Comment by blgm** [comment]
Hi @fhwsuper, the error `line 1: syntax error near unexpected token` typically comes from `bash` rather than from `ginkgo`. Could you check that `ginkgo` is a valid binary executable file for the platform that you're on? For instance when I run `file ginkgo`, I get:
```
ginkgo: Mach-O 64-bit executable x86_64
```

**Comment by fhwsuper** [comment]
root@secure-lasers-2:/software/ginkgo-1.14.0/bin# bash -version
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
root@secure-lasers-2:/software/ginkgo-1.14.0/bin#

root@secure-lasers-2:/software/ginkgo-1.14.0/bin# file ginkgo
ginkgo: current ar archive

----------------------------------------------------------------------------
The base version is 4.4.19. My build is "go build -o ./bin/ginkgo". Is it correct? Should other parameters be used when build?

**Comment by blgm** [comment]
Hi @fhwsuper, the output of the `file` command suggests that the `ginkgo` file is not an executable file. I think this is because you are trying to build `github.com/onsi/ginkgo`, when you actually need to build `github.com/onsi/ginkgo/ginkgo` (note the extra `ginkgo`). This has confused many people including myself. If you run `go build -o ./bin/ginkgo` in the `ginkgo/ginkgo` directory then you should get a valid executable file.

Typically users do not use `go build` (although it's perfectly ok to do so), instead they use one of the methods documented here: https://github.com/onsi/ginkgo#getting-started

**Comment by fhwsuper** [comment]
Thank you! The correct build path is /onsi/ginkgo/ginkgo.

**Comment by blgm** [comment]
It sounds like this issue is now resolved, but please re-open if that's not the case.
