### ISSUE TITLE
Unable to use ginkgo in travis CI

### ISSUE THREAD

**Issue by prameshj** [onsi/ginkgo#727]
I am trying to use ginkgo as part of the Travis CI for http://github.com/kubernetes/dns.

I tried a few different configs and no success so far. Previously we had a hack that re-built the same ginkgo in the vendor directory and built that. When switching to go modules, that stops building correctly, so I am trying to install ginkgo as part of the travis workflow:
https://github.com/kubernetes/dns/pull/409/files

This is the run when using the travis.yml recommended in this repo:
https://travis-ci.org/github/kubernetes/dns/builds/735087680
https://github.com/onsi/ginkgo/blob/master/.travis.yml

The repo already imports ginkgo into vendor since some of the test code depends on it. If I use "go get github.com/onsi/ginkgo/ginkgo" in the travis yml, I see the error:
https://travis-ci.org/github/kubernetes/dns/builds/734578589

```
goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000078180, 0xa10fa0, 0xeb8680, 0xc00002a7f0, 0xb, 0x97d67a, 0x2a)
	/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/flag/flag.go:848 +0x4ae
flag.(*FlagSet).Int64Var(...)
	/home/travis/.gimme/versions/go1.13.15.linux.amd64/src/flag/flag.go:673
k8s.io/dns/vendor/github.com/onsi/ginkgo/config.Flags(0xc000078180, 0x967c4a, 0x6, 0x1)
	/home/travis/gopath/src/k8s.io/dns/vendor/github.com/onsi/ginkgo/config/config.go:68 +0x114
k8s.io/dns/vendor/github.com/onsi/ginkgo.init.0()
	/home/travis/gopath/src/k8s.io/dns/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:55 +0x59
```

I guess that is because the flag is set by the init() in the vendor package and the one downloaded as part of "go get"?

**Comment by blgm** [comment]
Hi @prameshj. There are projects successfully using Go Modules, vendoring, Ginkgo and Travis CI. such as https://github.com/cloudfoundry/cli

I'm not sure why it's not working in `kubernetes/dns`. A common unexpected behaviour with Go Modules is that by default it will download packages over the network in preference to using the vendored files. I notice that the vendored version of Ginkgo used is v1.6.0 which is over two years old. It might be worth updating to a newer version to check whether there has been an accidental breaking change in Ginkgo.

**Comment by prameshj** [comment]
Thanks @blgm! I will try updating to a newer version and try. I see https://github.com/cloudfoundry/cli/blob/master/.travis.yml  gets ginkgo but does not actually invoke "ginkgo <test>" as part of the workflow. I was hitting the "flag redefined" error in that step. Do you know of another example that does something similar?

**Comment by blgm** [comment]
Good point, and I can't think of a project that does this off the top of my head...

But I did come across issue #234 that looks very similar to what you're seeing. Looks like people were able to fix their issue by fixing some vendoring issues. Would you mind taking a look and seeing whether or not you think it might be related?

**Comment by prameshj** [comment]
> Good point, and I can't think of a project that does this off the top of my head...
> 
> But I did come across issue #234 that looks very similar to what you're seeing. Looks like people were able to fix their issue by fixing some vendoring issues. Would you mind taking a look and seeing whether or not you think it might be related?

I did see the same issue as well, but the ginkgo version in the dns repo does not use extensions/tables.

**Comment by blgm** [comment]
Although the title of #204 is about the Table extension, [someone comments](https://github.com/onsi/ginkgo/issues/234#issuecomment-196344992) that it has been seen by people who are not using Table. Onsi [explains](https://github.com/onsi/ginkgo/issues/234#issuecomment-196645747) that the issue is caused when some Ginkgo files are loaded from `$GOPATH` and some are loaded from `vendor/`, which could be what's going on here. The effect is that Ginkgo's `init()` is called twice, which looks very similar to what's being seen.

I said in my last response that I couldn't think of an example project, so I created an example [ginkgo-vendor](https://github.com/blgm/ginkgo-vendor), and Travis [does pass](https://travis-ci.com/github/blgm/ginkgo-vendor/builds/189693632). However if you look at the log closely, Ginkgo is being downloaded over the network, which goes against the idea of using vendoring. So I would not recommend this approach.

Because Go Modules only vendors files that it knows are needed, a better approach is to use a [tools package](https://github.com/onsi/ginkgo#go-module-tools-package) to make Go Modules aware that the Ginkgo command is needed. I've added a [tools](https://github.com/blgm/ginkgo-vendor/tree/tools) branch to the example repo that demonstrates this. The [Travis log](https://travis-ci.com/github/blgm/ginkgo-vendor/builds/189694284) does not show anything being downloaded from the network, and you can see that the vendored Ginkgo directory contains more files.

The `-mod=vendor` build flag which forces Go to use only files in `vendor/`. There's more detail in `go help modules`.

**Comment by prameshj** [comment]
Thanks, this helps a lot. The dns repo currently does not use Go modules. I have another PR where i am migrating to go modules. I applied a change similar to what you added with the "-mod-vendor" flag, but that fails as well.

```
0.02s$ GOFLAGS="-mod=vendor" go install github.com/onsi/ginkgo/ginkgo
can't load package: package github.com/onsi/ginkgo/ginkgo: cannot find package "github.com/onsi/ginkgo/ginkgo" in any of:
	/home/travis/.gimme/versions/go1.13.linux.amd64/src/github.com/onsi/ginkgo/ginkgo (from $GOROOT)
	/home/travis/gopath/src/github.com/onsi/ginkgo/ginkgo (from $GOPATH)
The command "GOFLAGS="-mod=vendor" go install github.com/onsi/ginkgo/ginkgo" exited with 1.
0.15s$ GOFLAGS="-mod=vendor" ginkgo test/e2e
ginkgo: command not found
The command "GOFLAGS="-mod=vendor" ginkgo test/e2e" exited with 127.
```

This is the run - https://travis-ci.org/github/kubernetes/dns/builds/735417790

**Comment by blgm** [comment]
@prameshj, Go Modules does static analysis of the Go code and will only add things to `vendor/` that it sees being used. It does not read the `.travis.yml` file, so Go Modules is not adding the Ginkgo command to `vendor/` because it thinks it is unused.

The solution is to introduce a [tools package](https://github.com/onsi/ginkgo#go-module-tools-package) which makes Go Modules think that the Ginkgo command is in use, so it will add it to `vendor/`.

**Comment by prameshj** [comment]
Thanks so much @blgm ! I was able to get this working with the tools package and the migration to go modules + ginkgo 1.14.
https://travis-ci.org/github/kubernetes/dns/builds/736181135
