### ISSUE TITLE
Ginkgo doesn't implement testing.T.TempDir

### ISSUE THREAD

**Issue by tomqwpl** [onsi/ginkgo#743]
Perhaps I'm misunderstanding how I'd do this, but I wanted to use the TempDir function on testing.T in order to create a temporary directory in my tests.
Naively I used GinkgoT().TempDir() since I assumed that GinkgoT gave me access to the original testing.T, but it appears that this is not the case.
It appears GinkgoT().TempDir() always returns blank.

Temporary directories are very useful in tests, and I'd rather have one that was managed for me, cleaned up, and in a sensible place, rather than me using the ioutils.TempDir function with a random base directory and having to clean the result up myself.

**Comment by onsi** [comment]
Ginkgo does not currently support `testing.T.TempDir()` because Ginkgo doesn't have a mechanism yet to register cleanup functions outside of the developer formally constructing an `AfterEach` themselves.  Adding support for `T.Cleanup()` (which would basically inject new `AfterEach` blocks out of band with the explicit test structure crated by the developer) is something I'm considering for 2.0... though I'm on the fence at the moment.

For the specific problem you're trying to solve I tend to add a snippet like this to the top of my suite file:

```
var tmpDir string

var _ = BeforeEach(func() {
    var err error
    tmpDir, err = inutil.TempDir()
    Expect(err).NotTo(HaveOccurred())
})

var _ = AfterEach(func() {
    Expect(os.RemoveAll(tmpDir)).To(Succeed())
})
```

yes it's some amount of boiler plate.  One benefit, however, is when I need to debug a failing test and inspect the contents of the `tmpDir` I simply fuss the test and comment out the `RemoveAll` in the `AfterEach` to get a fast feedback loop.

**Comment by onsi** [comment]
I'm aiming to add support for this in [v2](#711)

**Comment by onsi** [comment]
This is now fixed in V2.  Docs for using the beta are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta).

`GinkgoT()` now supports `TempDir()` and `Setenv()`.  More importantly, Ginkgo implements `DeferCleanup` which enables support for helper functions like this that perform some set up that then must be cleaned up at the appropriate time in the test lifecycle.
