### ISSUE TITLE
feature proposal: ItTable

### ISSUE THREAD

**Issue by noah-friedman** [onsi/ginkgo#790]
Similar to the DescribeTable in `extensions/table`, it would be useful for readability to have an `ItTable` option. I intend to fork and make a PR implementing this.
(I'm still very new to creating issues on open source projects, so if I've done something wrong in terms of phrasing or steps of action, please let me know 😊)

**Comment by onsi** [comment]
hey @noah-friedman - couple of things:
1. i'm going to be making the table extension part of core in [v2](#711) - doesn't change the pr but just an fyi.
2. can you say more about the problem you are trying to solve?  is `ItTable` a synonym for `DescribeTable`?  Or are you needing different functionality?

**Comment by noah-friedman** [comment]
Thanks for letting me know about that first thing.
I'm planning to make `ItTable` work similarly to `DescribeTable` but not the same. The problem I have with `DescribeTable` from a BDD perspective is that it's not always the right way I want to explain my tests. I often find myself trying to structure my tests like this:
```go
/* 
 * The IsItHelloWorld function should return true if the 
 * input is "Hello World" and should return false otherwise.
 */
var _ = Describe("the IsItHelloWorld function", func() {
    ItTable("should return %b when supplied with %s", 
    // ^ Implementing a format string here, similar to Jest's test.each
        func(output bool, input string) {
            Expect(IsItHelloWorld(input)).To(Equal(output))
        },
        Entry(false, "foobar"), 
        /* ^
         * Not requiring a description of the Entry
         * Might change the current 'Entry' to 'DescribeEntry' and create a new 'ItEntry', OR 
         * Remove the description argument from the current 'Entry' while still expecting 
           it and throwing an error if the first argument in the 'Entry' is not a string.
         */
         Entry(true, "Hello World"),
    )
})
```
but I can't with the `DescribleTable`. As I mentioned in the code block, I'm somewhat taking inspiration from Jest's [`test.each`](https://jestjs.io/docs/api#testeachtablename-fn-timeout).

**Comment by noah-friedman** [comment]
Something I never actually knew about the DescribeTable was that you could have parametric descriptions. I still think it would be nice to be able to supply a format string instead of a function, but that's probably a different issue altogether.

**Comment by noah-friedman** [comment]
Instead of using a format string, I will try to use the already present option to have a parametric description for entries in the ItTable description itself.

**Comment by noah-friedman** [comment]
Instead of using a format string I think it actually makes sense to use the logic for using a function as a description in an `Entry` and apply it to the description of an `ItTable`.

**Comment by noah-friedman** [comment]
@onsi should I wait to create the code PR until I'm ready to create the docs PR as well?

**Comment by onsi** [comment]
hey i'm out of town the next few days but will take a look at this on tuesday/wednesday

**Comment by onsi** [comment]
hey @noah-friedman - i'm back in town now.  Sorry I couldn't be more responsive - I was out in the middle of nowhere, Colorado.

I appreciate the problem you're trying to solve here and it's one I've bumped into as well.  I think I'd like to take a different approach, however.  Rather than add a new `ItTable` function with a structure that's parallel to `DescribeTable` I'd prefer to teach `DescribeTable` how to handle this use-case.

Specifically I'd like to allow the user to explicitly convey their intention to `DescribeTable` and `Entry` and then use the Go's type system & reflect package to implement the desired behavior.  Concretely this would look like:

```
DescribeTable("Table Description", <optional entry description>, func(A, B, C) {},
    Entry(A, B, C),
    Entry("Override Entry Description", A, B, C),
    Entry(func(A, B,C) string { return "Custom Override Description"+A}, A, B, C),
)
```

Where `<optional entry description>` can be any of:

- Blank (i.e. not present).  In which case this will generate entries titled: `"Table Description: [A, B, C]"`, `"Override Entry Description"`, `"Custom Override Description" + A`
- A string (e.g. `"Entry Description"`) In which case this will generate entries titled: `"Entry Description: [A, B, C]"`, `"Override Entry Description"`, `"Custom Override Description" + A`
- A string of `type EntryFormat string` - which will be interpreted as a format string with `A, B, C` passed to it.  So, for example: `DescribeTable("Table Description", EntryFormat("Case %s: B is %d, C is %d), ...)` would render as `"Case foo: B is 3, C is 17"` if `A` is `foo` ,`B` is `3`, `C` is `17`.
- A function that returns `string` - which will be called for each Entry to generate its string description.

I'd then also extend `Entry` to be able to handle `EntryFormat` as well.  This would give folks a massive amount of flexibility, be 100% backward compatible, but also get out of the way when you just want a table and don't want to bother with describing every little thing.  I'll plan to implement this as part of the V2 work when I migrate table over but if you'd like to implement this approach on V1 to have it sooner that would be great.

**Comment by noah-friedman** [comment]
That sounds like a great idea, I'll wait for V2! Feel free to mark this as closed, I'll close the PRs.

**Comment by onsi** [comment]
hey @noah-friedman - it sure took forever but the V2 beta has this functionality now.  Docs for using the beta are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta) - and details on the new table behavior are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/index.md#generating-entry-descriptions)
