### ISSUE TITLE
Skipped test descriptions are not reported

### ISSUE THREAD

**Issue by criscola** [onsi/ginkgo#807]
When reading the docs: 

> 
> --noisySkippings=false
> 
> By default, Ginkgo’s default reporter will provide detailed output for skipped specs. You can set –noisySkippings=false to suppress this behavior.

My command is:

```
ginkgo --skip=".*\[slow].*" pkg/database 
```

My output is:

```
Running Suite: Database package suite
=====================================
Random Seed: 1621252667
Will run 7 of 9 specs

SS•••••••
Ran 7 of 9 Specs in 0.000 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 2 Skipped
PASS

Ginkgo ran 1 suite in 9.613135426s
Test Suite Passed
```

I can't see in any way the descriptions of the skipped tests. I also tried playing with some CLI flags such as `--noisySkippings=true` with no luck.

**Comment by onsi** [comment]
hey @criscola -- yeah the behavior of `--noisySkippings` is kinda weird.  It's actually being removed in [v2](#711) because I don't think it's providing a ton of value.

There are two basic ways to skip tests in Ginkgo.  Like you're doing with `--skip` which filters out tests by name.  And by calling `Skip("skipped because of foo")` within a test programatically.  `--noisySkippings` controls whether the latter class of skips emits the skip reason (e.g. `"skipped because of foo"` in this example).

Maybe, to switch gears, let me ask: what problem are you trying to solve?  Are you wanting to know what tests were skipped?  You can run `ginkgo --skip=".*\[slow].*" --v pkg/database` to get more output - and you can throw in `--dryRun` if you just want to see what _will_ run without actually having to run the test.

As a sidebar: v2 is going to include support for spec labels which will make this sort of filtering much easier.

**Comment by criscola** [comment]
Hi @onsi, thanks for your rapid response. I'm looking forward to work with the `v2` of Ginkgo, especially spec labels which I essentially implemented through string formatting, some "enums" and regex. 

I tried with `--v` as well, but what I see is this:

```
[..]
------------------------------
SS
------------------------------
[..]
```
I would like to see the text associated with each `It` or  `Describe` clauses, so that I could check that my regex actually skipped the tests I didn't want to run.

**Comment by onsi** [comment]
welp - my bad, sorry.  I was misremembering Ginkgo's behavior.  you're correct there's currently no way to view the set of skipped specs which is an oversight.  I'll make sure this is possible in v2 but I'm not planning on making too many more changes on V1.

**Comment by criscola** [comment]
Got it, thanks.

**Comment by shazib-summar** [comment]
cc @onsi 

hey, hope youre doing good. Was this implemented in v2? I'm using v2, but my skipped tests do not show the passed string in the logs.

What I mean is that the report still shows
```
SS•••••••
```
How can I configure it to show the full skip message?

**Comment by onsi** [comment]
hey - it looks like I've gone back and forth on this a bit in the code.  I think in earlier versions of V2 I had it always emitting the skip string passed to `Skip(...)` - but after some feedback from the community (I think, specifically, the k8s test suite that uses `Skip(<reason>)` a lot) there was a sense that the specs were getting noisy.  So, now, the skip reason only appears in the JSON and JUnit report files unless you are running with `-vv` in which case you will see them emitted to the console (along with a whole lot more).

I _could_ add a (yet another) flag to control whether the skip reason is shown or not regardless of verbosity level.  Or I could walk things back so that the reason appears with `-v` and not just `-vv` and see who, if anyone complains about it.

Any thoughts from y'all?

**Comment by shazib-summar** [comment]
hey @onsi , thanks a lot for getting back. I was going through some other issues, love how much you interact with the community.

I think the best case here would be a separate flag (`-vs` or something) for skip reasons. This will
1. Allow user to only view spec timeline on i) failures and ii) skips (these are the ones I'm interested in)
2. Allow user to not get log pollution from passed testcases. (`-v` and `-vv` both print timelines for passed testcases as well)
3. Make this feature a non-breaking change (k8s community wont complain)

thanks,

**Comment by onsi** [comment]
Hey @shazib-summar - yeah the more i think about it the more it makes sense to make the verbosity configurable as a function of the spec state.

I'd keep the existing behavior for `-v` and `-vv` but introduce something like `-v-fail`/`-vv-fail` and `-v-skip`/`-vv-skip` to turn verbosity/very-verbose on for specs that fail/skip.

I'm realizing that this is a feature I've been wanting as well.  I sometimes want `-vv` to understand exactly where a spec has failed but only want it for failures, not for all specs (which is an overwhelming amount of output).  `--vv-fail` feels like a good solution and I could imagine most CI systems always running with `--vv-fail` to get maximum output when a failure occurs.

**Comment by HansvdLaanNedap** [comment]
Hey @osni, also thanks for getting back to us and the interaction with the community. I'm a fan of your proposal.

Your proposal would also solve my use-case. I'd like to use skip to keep track of known failures. Having a -v-skip command which outputs the reason the test was skipped would help to get an overview of all know failures.
