### ISSUE TITLE
 Ginkgo SynchronizedBeforeSuite Parallel access array

### ISSUE THREAD

**Issue by chenpfeisoo** [onsi/ginkgo#808]
I define an array in the node1body of Ginkgo SynchronizedBeforeSuite. When I execute cases in parallel, I need to control each case to obtain an array value that does not repeat. I have tried many times, and the result each time does not meet the requirements. Is there a demo for this scenario. Thank you very much
@onsi

**Comment by onsi** [comment]
hey @chenpfeisoo it would be helpful to have a little more information so I can best help you.  I've rarely seen a case like this and want to make sure I'm understanding the actual problem you are trying to solve so I can help you solve it.  Since Ginkgo spawns multiple processes to run in parallel coordination between the processes can take more work.

Some basic approaches:

## Pre-distribute the array

If you can *consistenly* compute the array (i.e. every parallel process will compute the same array) before the test hierarchy is constructed _and_ each test is basically doing the same thing with the array element then you can do this:

```go
var arr TheArray
func TestMySuite(t *testing.T) {
    arr = ConstructTheArray()
    RegisterFailHandler(Fail)
    RunSpecs(t, "My Suite")
}

var _ = Describe("test the array", func() {
    for _, el := range arr {
        el := el
        It(fmt.Sprintf("does something with %s", el), func() {
                 // do stuff with el
        })
    }
})
```

## Do you really need an array?

I've seen cases where folks are trying to use an array to make sure the tests running in parallel don't accidentally interact (e.g. the array is a list of namespaces and each test gets a unique namespace so it can't pollute other tests).  You can usually resolve that kind of problem by generating a random namespace in a `BeforeEach` or by using `GinkgoParallelNode()` to get the index of the current parallel process and use that index to shard things (e.g. if each test needs a unique directory you can either make a fresh temp directory in a `BeforeEach` or make a directory called `fmt.Sprintf("./mydir-%d", GinkgoParallelNode())` - in either case you'll be guaranteed that the tests don't interact.

## Server/Client model

If you really do need to centralize control over access to the array please share your use case as I'd like to learn more about what you're doing!  You can do it like this (this is a sketch that uses [ghttp](https://onsi.github.io/gomega/#ghttp-testing-http-clients), you can also just use `net/http` if you'd like):

```
var getNextEl func() El

var _ = SynchronizedBeforeSuite(func() []byte {
    arr := ConstructTheArray()
    idx := 0
    lock := &sync.Mutex{}
    server := ghttp.NewServer()
    server.RouteToHandler("GET", "/next", func(w http.ResponseWriter, r *http.Request) {
        lock.Lock()
        defer lock.Unlock()
        json.NewEncoder(w).Encode(arr[idx])
        idx += 1
    })
    return []byte(server.Addr())
}, func(data []byte) {
   addr := string(data)
   getNextEl = func() El {
       resp, err := http.Get(addr+"/next")
       Expect(err).NotTo(HaveOccurred())
       defer resp.Body.Close()
       var el El
       err = json.NewDecoder(resp.Body).Decode(&el)
       Expect(err).NotTo(HaveOccurred())
       return el
   }
})

var _ = It("gets an el and does something", func() {
    el := getNextEl()
    // do stuff with el
})
```

**Comment by chenpfeisoo** [comment]
@onsi Thank you for your warm reply

First of all, I'm sorry I didn't clearly describe my problem. Here are some of my test code

Before the test, I created a group of cluster resources. Each test case uses two clusters. I want to ensure that the parallel tests are allocated differently each time

I can't accurately control the parallelism here. As a result, the clusters obtained by the three cases are the same. I hope that the clusters obtained by each test are different, and the two clusters in a case are also different

```go
var _ = SynchronizedBeforeSuite(func() []byte {
	totaltkeTestClusters = tcm.PreTkeClusters("gwtest-", []string{
		cluster.MANAGED_CLUSTER, cluster.MANAGED_CLUSTER,
		cluster.MANAGED_CLUSTER, cluster.MANAGED_CLUSTER,
		cluster.MANAGED_CLUSTER, cluster.MANAGED_CLUSTER})
	initCluster_1()
	return nil
}, func(data []byte) {
})

var _ = BeforeEach(func() {
	initCluster_2()
})

func initCluster_2() {
	managerCluster = *findTke()
	managerCluster_ = *findTke()
}

var testClusters []map[*tcm.TkeTestCluster]bool

func initCluster_1() {
	for _, v := range totaltkeTestClusters {
		testClusters = []map[*tcm.TkeTestCluster]bool{
			{
				&v: false,
			},
		}
	}
}

func findTke() *tcm.TkeTestCluster {
	var lock sync.Mutex
	for _, v := range testClusters {
		lock.Lock()
		for k := range v {
			if v[k] {
				continue
			} else {
				v[k] = true
				lock.Unlock()
				return k
			}
		}
	}
	panic("Failed to allocate cluster......")

}


//case
var _ = Describe("test", func() {
	It("test1", func() {
		klog.Info(managerCluster.Tkeclusterid, "  ", managerCluster_.Tkeclusterid)
	})
	It("test2", func() {
		klog.Info(managerCluster.Tkeclusterid, "  ", managerCluster_.Tkeclusterid)
	})
	It("test3", func() {
		klog.Info(managerCluster.Tkeclusterid, "  ", managerCluster_.Tkeclusterid)
	})
})
```

**Comment by chenpfeisoo** [comment]
![image](https://user-images.githubusercontent.com/18147157/118658130-b3342200-b81e-11eb-99a3-aac3ccf325db.png)

**Comment by onsi** [comment]
OK - so a few options:

## Option 1 - Create a new pair of clusters before every test

This option ensures that you have a fresh pair of clusters for each test.  The clusters will never be accessed by more than one test in parallel.  You typically use an option like this if you need a fresh pair and cannot clean them up between tests.

```go
var managedCluster, managedCluster_ *tcm.TkeTestCluster
var _ = BeforeEach(func() {
    clusters := tcm.PreTkeClusters("gwtest-", []string{cluster.MANAGED_CLUSTER, cluster.MANAGED_CLUSTER})
     managedCluster = clusters[0]
     managedCluster_ = clusters[0]
})
```

The downside here is that the tests will be slow if cluster creation is slow.

## Option 2 - Create a pair of clusters for each parallel Ginkgo process

This option creates a single of clusters for each parallel Ginkgo process.  It is guaranteed that two different tests will not access the same cluster in parallel however it is possible for the cluster to be reused between tests.  For cases like this I typically see some sort of clean-up code in an `AfterEach`

```go
var managedCluster, managedCluster_ *tcm.TkeTestCluster
var _ = BeforeSuite(func() {
    clusters := tcm.PreTkeClusters("gwtest-", []string{cluster.MANAGED_CLUSTER, cluster.MANAGED_CLUSTER})
     managedCluster = clusters[0]
     managedCluster_ = clusters[0]
})

var _ = AfterEach(func() {
    cleanUp(managedCluster)
    cleanUp(managedCluster_)
})
```

I suspect option 2 is what you want.

**Comment by chenpfeisoo** [comment]
@onsi Thank you for your advice, issue. I'm closed
