### ISSUE TITLE
Ginkgo supports mixed execution of parallel test and serial test

### ISSUE THREAD

**Issue by chenpfeisoo** [onsi/ginkgo#810]
Some of my test projects can be executed in parallel, and some need to be executed serially due to the high cost of testing, but I don't want to perform multitasking, so I need a `ginkgo  -r --nodes=x  --suitefilter --suitchioce`. I don't know whether there is a similar scheme or whether Ginkgo 2.0 thinks it is necessary?

**Comment by onsi** [comment]
hey @chenpfeisoo with V1 the only thing you can do is specify --skipPackage to skip packages.  so a common pattern is:

```bash
ginkgo -r -nodes=X -skipPackage=package1,package2
ginkgo  -nodes=1 package1 package2
```

I'm aiming to do better with V2 by introducing a capability to provide per-package configuration that can be committed to Git.  With this packages will be able to set (for example) a maximum number of nodes so that some will run in parallel and others will not  and you can just do `ginkgo -r -nodes=X` and trust Ginkgo to do the right thing.

**Comment by onsi** [comment]
hey @chenpfeisoo - you can't specify this on a per-package basis yet... however you _can_ mark individual tests or containers as `Serial` in V2 now.  Docs for using the beta are [here](https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#using-the-beta) - give it a try!

**Comment by TheDiveO** [comment]
`Serial` is really useful! I'm now upgrading to v2 beta, as I have some container-workload related tests that should not be run in parallel because of high latencies due to container image unpacking and preparations. In the past I've thus never used `--nodes`, now it is sweet and safe to use.

**Comment by onsi** [comment]
sweet @TheDiveO - glad you're able to put this to use :)
