### ISSUE TITLE
Vulnerability CVE-2020-29652 reported

### ISSUE THREAD

**Issue by zzxwill** [onsi/ginkgo#816]
My project depended on github.com/onsi/ginkgo v1.16.2 and it's reported a vulnerability CVE-2020-29652.

ID | SEVERITY | PACKAGE | VERSION | FIXED IN
-- | -- | -- | -- | --
&nbsp; | CVE-2020-29652 | HIGH | golang.org/x/crypto | v0.0.0-20200622213623-75b288015ac9 | v0.0.0-20201216223049-8b5274cf687f

golang: crypto/ssh: crafted authentication request can lead to nil pointer dereferenceA nil pointer dereference in the golang.org/x/crypto/ssh component through v0.0.0-20201203163018-be400aefbc4c for Go allows remote attackers to cause a denial of service against SSH servers.Updated&nbsp;6 months agoCVSS&nbsp;v3&nbsp;Vector(SOURCE:&nbsp;nvd)SCORE:7.5EXPLOITABILITY METRICSATTACK VECTOR:PhysicalLocalAdjacent NetworkNetworkATTACK COMPLEXITY:HighLowPRIVILEGES REQUIRED:HighLowNoneUSER INTERACTION:RequiredNoneSCOPE:UnchangedChangedIMPACT METRICSCONFIDENTIALITY:NoneLowHighINTEGRITY:NoneLowHighAVAILABILITY:NoneLowHigh

After a simple investigation, the issue locates in package golang.org/x/tools.

```
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/onsi/ginkgo git:(master) go mod graph | grep " golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9"
golang.org/x/net@v0.0.0-20201021035429-f5854403a974 golang.org/x/crypto@v0.0.0-20200622213623-75b288015ac9
➜  /Users/zhouzhengxi/Programming/golang/src/github.com/onsi/ginkgo git:(master) go mod graph | grep " golang.org/x/net@v0.0.0-20201021035429-f5854403a974"
golang.org/x/tools@v0.0.0-20201224043029-2b0845dc783e golang.org/x/net@v0.0.0-20201021035429-f5854403a974
```

**Comment by blgm** [comment]
Hi @zzxwill. Ginkgo does have `golang.org/x/crypto` in the `go.sum` file, but not in the `go.mod` file. My interpretation of this is that Ginkgo doesn't directly use `golang.org/x/crypto` but some of the dependencies of Ginkgo may use it - or did in the past. Because of Go bug https://github.com/golang/go/issues/36460, the `go.sum` file for Ginkgo contains a number of historical cyclical dependencies. For instance `github.com/fsnotify/fsnotify` is found in `go.sum` but stopped being actually used some time ago.

So I think Ginkgo is not vulnerable to this CVE. Normally I would try to bump dependencies even if I don't think a CVE is relevant because it's better to look safe. However because of Go bug https://github.com/golang/go/issues/36460, I don't think bumping dependencies will remove the vulnerable version of `golang.org/x/crypto` from the `go.sum` file.

I would be interested if anyone can suggest something that could be done about this, but I think we need to wait for the Go bug to be fixed.
