### ISSUE TITLE
[ginkgo 2] Parallel tests failing on Focal distro

### ISSUE THREAD

**Issue by hhsecond** [onsi/ginkgo#858]
Hi, we have been migrating to ginkgo 2 from ginkgo 1. We were using Bionic originally but wanted to move to focal. Here is the Dockerfile for the image

```
FROM mcr.microsoft.com/playwright:focal

RUN apt-get update && apt-get install -y \
    software-properties-common \
    curl \
    libpython3.8-dev \
    python3.8-dev \
    libwoff1 \
    libopus0 \
    libwebp6 \
    libwebpdemux2 \
    libenchant1c2a \
    libgudev-1.0-0 \
    libsecret-1-0 \
    libhyphen0 \
    libgdk-pixbuf2.0-0 \
    libegl1 \
    libnotify4 \
    libxslt1.1 \
    libevent-2.1-7 \
    libgles2 \
    libvpx6 \
    libnss3 \
    libxss1 \
    libasound2 \
    fonts-noto-color-emoji \
    libdbus-glib-1-2 \
    libxt6 \
    ffmpeg

RUN curl -fsSL -o go.tar.gz https://dl.google.com/go/go1.16.4.linux-amd64.tar.gz  && tar -xvf go.tar.gz -C /usr/lib
ENV GOTOOLDIR=/usr/lib/go/pkg/tool/linux_amd64
ENV PATH=/usr/lib/go/bin:$PATH
ENV GOBIN=/usr/local/bin
RUN go env
RUN go install github.com/onsi/ginkgo/ginkgo@ver2 && \
    go install github.com/mxschmitt/playwright-go/cmd/playwright@latest && \
    playwright install --with-deps

ENV GOBIN=""
```

When running the tests using multiple nodes (`--nodes` > 1), I see this issue

```
  rpc: can't find method Server.BeforeSuiteSucceeded
  In [SynchronizedBeforeSuite] at: /grid-backend/tests/api/bootstrap_test.go:41
------------------------------
[SynchronizedBeforeSuite] [FAILED] [0.052 seconds]
[SynchronizedBeforeSuite]
/grid-backend/tests/api/bootstrap_test.go:41

  Node 1 disappeard before SynchronizedBeforeSuite could report back
    Ginkgo parallel process #1 disappeared before the first
    SynchronizedBeforeSuite function completed.  This test suite will now abort.
```

**Comment by onsi** [comment]
hey @hhsecond I _think_ there's a version mismatch between the ginkgo CLI and the ginkgo library you've got in your go.mod.  I [recently](https://github.com/onsi/ginkgo/commit/e28ffdd5043ee72ea36766fc237ca53820717cfd) changed the internal contract between Ginkgo's server/client RPC api.  I bet `go install github.com/onsi/ginkgo/ginkgo@ver2` in your docker file is grabbing the tip of the `ver2` branch whereas your `go.mod` is locked to whatever sha of `ver2` was the tip when you last ran `go get github.com/onsi/ginkgo@ver2`.  (The lack of semver during the RC phase is partly to blame here, this should all be much easier to track once v2 goes GA).

I think you have two options:

1. Bump to the latest version of the ginkgo library `go get github.com/onsi/ginkgo@ver2`
2. Run the version of the ginkgo cli associated with the ginkgo library in your package when you run tests in docker.  I'm pretty sure you can accomplish this from your package directory by running `go run github.com/onsi/ginkgo/ginkgo` instead of compiling and running `ginkgo`.  That will guarantee that the sha in your go.mod governs both the library version and the cli version.

**Comment by hhsecond** [comment]
Oh you are amazing! Thank you. Closing the issue
