### ISSUE TITLE
Feature Request: --onlyChanged flag

### ISSUE THREAD

**Issue by SamuelCabralCruz** [onsi/ginkgo#863]
I was wondering if there was any way to reproduce the --onlyChanged flag when using jest with ginkgo.

This would be really helpful whenever we want to create a pre-commit hook while restraining number of tests to be run before the commit.

I saw that there was a watch cli which must already do all the logic of detecting changes using suites dependencies, so I guess it should not be that hard to implement.

Anyway, I know most of the efforts are currently invested into the ginkgo v2, so this issue can also act as a proposal for v2!

**Comment by onsi** [comment]
hey @SamuelCabralCruz - I'm going to avoid adding any more scope to v2 at this point since it's so close to release.  this would not be crazy hard to implement, no, but I'm not super confident in the value... I tend to run all the tests in my pre-commit ritual; and my slow test suites tend to be integration tests which will basically always need to rerun because you typically can't really guarantee that a change doesn't affect an integration tests as the integration tests pull together all/most components and so are likely to be flagged as "changed".

what I usually see is some sort of filtering mechanism to have non-slow tests run locally (with v2 you can use spec labels to flag specs as "slow" then use a `--label-filter`) and then let CI deal with then slow stuff out of band.

**Comment by SamuelCabralCruz** [comment]
@onsi I totally agree with you and this is also what I ended up doing while I was waiting for your feedback.
Also, go tests are much faster to execute than node ones so it is not to big of a problem.

We can close this issue then!

**Comment by onsi** [comment]
great thanks!
