### ISSUE TITLE
Variable value leaks between `Context` blocks

### ISSUE THREAD

**Issue by antoineco** [onsi/ginkgo#886]
**Version:** Ginkgo v2.0.0

Consider the following (simplified) test spec with a `subscriptionID` variable declared at the top scope:

```golang
var _ = Describe("My Test", func() {

	var subscriptionID string

	Context("Real values", func() {

		subscriptionID = os.Getenv("SUBSCRIPTION_ID")

		BeforeEach(func() {
			azure.CreateResourceGroup(subscriptionID, "foo")
		})
		AfterEach(func() {
			azure.DeleteResourceGroup(subscriptionID, "foo")
		})

		Specify("Something", func() {
			// ...
		})
	})

	Context("Fake values", func() {

		BeforeEach(func() {
			subscriptionID = "00000000-0000-0000-0000-000000000000"
		})

		Specify("Something", func() {
			// ...
		})
	})
})
```

Occasionally, `azure.CreateResourceGroup()` is called with a `subscriptionID` value of `00000000-0000-0000-0000-000000000000`, instead of the value read from the environment, although this value originates from a totally different Context:

```
Unable to create resource group: {"error":{"code":"SubscriptionNotFound","message":"The subscription '00000000-0000-0000-0000-000000000000' could not be found."}}
```

The full test code: https://github.com/triggermesh/triggermesh/blob/60d2bcda/test/e2e/sources/azureactivitylogs/main.go#

**Comment by onsi** [comment]
Hey there - the issue is that the context node is only run once during the tree construction phase.  Ginkgo wants you to "Declare in container nodes, initialize in setup nodes".  You can get the behavior you want with:

```go
var _ = Describe("My Test", func() {
	var subscriptionID string

	Context("Real values", func() {
		BeforeEach(func() {
         		subscriptionID = os.Getenv("SUBSCRIPTION_ID")
			azure.CreateResourceGroup(subscriptionID, "foo")
		})
		AfterEach(func() {
			azure.DeleteResourceGroup(subscriptionID, "foo")
		})

		Specify("Something", func() {
			// ...
		})
	})

	Context("Fake values", func() {

		BeforeEach(func() {
			subscriptionID = "00000000-0000-0000-0000-000000000000"
		})

		Specify("Something", func() {
			// ...
		})
	})
})
```

I'd recommend reading [this part of the docs](https://onsi.github.io/ginkgo/#mental-model-how-ginkgo-traverses-the-spec-hierarchy)  to build a mental model for how the test hierarchy is constructed and traversed and [this part in particular](https://onsi.github.io/ginkgo/#avoid-spec-pollution-dont-initialize-variables-in-container-nodes) covers the specific issue you're bumping into.

**Comment by antoineco** [comment]
Thanks for the quick answer @onsi!
The solution is to move the initialization to the `BeforeEach` understood.

However, how could the `00000000-0000-0000-0000-000000000000` value possibly end up being accessible to the first `Context`? Is this because nothing was writing a value in a setup node and therefore the initialization became order dependant?

**Comment by onsi** [comment]
The `subscriptionID` variable is shared between the two contexts, and Ginkgo randomizes the order of your specs.  Because of this you will  get `000-etc.` anytime the "Fake Value => Something"  spec runs before the "Real values => Something" spec.   Note that when a spec runs only the contents of the setup and subject nodes are invoked.  Not the contents of the container nodes - so the initialization in the container node is never called after the spec tree is first constructed.

FWIW I do suggest at least skimming the doc links I shared as they'll give you a stronger mental model of how this stuff works.

**Comment by antoineco** [comment]
Thanks again, everything is much clearer now 👍
