### ISSUE TITLE
Ginkgo stops processing in middle of JustAfterEach after failed assertion in JustBeforeEach

### ISSUE THREAD

**Issue by josh-ferrell** [onsi/ginkgo#959]
I'll start by saying this may be a failure to fully understand Ginkgo setup nodes on my part. I have a test that creates some public cloud infrastructure in a JustBeforeEach setup node, executes the test and tears down the infrastructure in JustAfterEach. If an assertion fails in the JustBeforeEach setup node Ginkgo will stop after func3 in the example below. If I move that assertion to the subject node and it fails the whole JustAfterEach is run. Is this expected behavior? 

```
ginkgo.JustAfterEach(func() {
	func1()
	func2()
	if condition {
		func3()
		func4()
		func5()
	}
})
```

**Comment by onsi** [comment]
Hey there - when a failure occurs within the body of a given node [Ginkgo halts execution of that node](https://onsi.github.io/ginkgo/#mental-model-how-ginkgo-handles-failure)` - any lines of code that occur after the failure point in that node will not run.  Ginkgo will then start cleaning up by running any relevant `AfterEach` nodes.

My best guess is that the `condition` statement in your `AfterEach` is only satisfied if some line of setup code in your `BeforeEach` successfully runs and that the failure that's happening in your `BeforeEach` is occurring _before_ that line.  (Does that make sense?  Happy to try to write that out with an example if it's difficult to parse)

I'd suggest taking a look at the `condition` to make sure it's actually what you need given this behavior - or if you need to tweak it.

Also happy to look at your code if it's open source.

**Comment by onsi** [comment]
Ah I see, sorry I didn't read your first post closely enough.  I bet this is what's happening:

When you put the assertions in the `JustBeforeEach` like this:

```go
JustBeforeEach(func() {
	//...
	CreateInfra()
	//...
	CreateInfra()

	ASSERTIONS()
	CreatePeering()
})
```

then `CreatePeering()` never runs becuase the `ASSERTIONS` fail and halt execution.  Ginkgo then moves on to the `JustAfterEach` and I _bet_ what's happening is a panic is occuring either because `cPeering` is still `nil` and you are trying to dereference it *or* `DeletePeering` is panicking because `CreatePeering never succeeded.  Unfortunately (and, at this point, there's not a lot I can do about this without some effort) Ginkgo only reports the first failure it sees in a spec and it swallows the panic generated by your `JustAfterEach` node.

The reason this _doesn't_ happen when you move `ASSERTIONS` into the `It` is because `CreatePeering` gets a chance to run and the `JustAfterEach` no longer panics.

I think you can replace

```go
if cPeering.VpcPeeringConnectionId != nil {
	shared.DeletePeering(e2eCtx, *cPeering.VpcPeeringConnectionId)
}
```

with

```go
if cPeering != nil && cPeering.VpcPeeringConnectionId != nil {
	shared.DeletePeering(e2eCtx, *cPeering.VpcPeeringConnectionId)
}
```

and things will work.

Alternatively you can use the new [`DeferCleanup`](https://onsi.github.io/ginkgo/#spec-cleanup-aftereach-and-defercleanup) in Ginkgo V2 to move the cleanup closer to the setup:

```
ginkgo.JustBeforeEach(func() {
	specName = "functional-test-extinfra-peered-internal-elb"
	requiredResources = &shared.TestResource{EC2Normal: 2 * e2eCtx.Settings.InstanceVCPU, IGW: 2, NGW: 2, VPC: 2, ClassicLB: 2, EIP: 5}
	requiredResources.WriteRequestedResources(e2eCtx, specName)
	Expect(shared.AcquireResources(requiredResources, config.GinkgoConfig.ParallelNode, flock.New(shared.ResourceQuotaFilePath))).To(Succeed())
	ginkgo.DeferCleanup(shared.ReleaseResources, requiredResources, config.GinkgoConfig.ParallelNode, flock.New(shared.ResourceQuotaFilePath))
	
	namespace = shared.SetupSpecNamespace(ctx, specName, e2eCtx)
	ginkgo.DeferCleanup(shared.DumpSpecResourcesAndCleanup, ctx, "", namespace, e2eCtx)

	ginkgo.By("Creating the management cluster infrastructure")
	mgmtClusterInfra.New(shared.AWSInfrastructureSpec{
		ClusterName:       mgmtClusterName,
		VpcCidr:           "10.0.0.0/23",
		PublicSubnetCidr:  "10.0.0.0/24",
		PrivateSubnetCidr: "10.0.1.0/24",
		AvailabilityZone:  "us-west-2a",
	}, e2eCtx)
	mgmtClusterInfra.CreateInfrastructure()
	if !e2eCtx.Settings.SkipCleanup {
		ginkgo.DeferCleanup(mgmtClusterInfra.DeleteInfrastructure)
	}

	ginkgo.By("Creating the workload cluster infrastructure")
	wlClusterInfra.New(shared.AWSInfrastructureSpec{
		ClusterName:       wlClusterName,
		VpcCidr:           "10.0.2.0/23",
		PublicSubnetCidr:  "10.0.2.0/24",
		PrivateSubnetCidr: "10.0.3.0/24",
		AvailabilityZone:  "us-west-2a",
	}, e2eCtx)
	wlClusterInfra.CreateInfrastructure()
	if !e2eCtx.Settings.SkipCleanup {
		ginkgo.DeferCleanup(wlClusterInfra.DeleteInfrastructure)
	}

	ginkgo.By("Creating VPC peerings")
	cPeering, _ = shared.CreatePeering(e2eCtx, mgmtClusterName+"-"+wlClusterName, *mgmtClusterInfra.VPC.VpcId, *wlClusterInfra.VPC.VpcId)
	if !e2eCtx.Settings.SkipCleanup {
		ginkgo.DeferCleanup(shared.DeletePeering, e2eCtx, *cPeering.VpcPeeringConnectionId)
	}
})
```

**Comment by josh-ferrell** [comment]
That makes so much sense I'm embarrassed. I just couldn't see it so I didn't think through that failure in the AfterEach node. Thanks again for all your help on this.

**Comment by onsi** [comment]
no worries - glad we could figure it out and sorry Ginkgo isn't more communicative about the second failure.
