### ISSUE TITLE
-v prints GinkgoWriter output twice

### ISSUE THREAD

**Issue by pohly** [onsi/ginkgo#967]
I am running with `-ginkgo.v -ginkgo.always-emit-ginkgo-writer=false` because I want to see output as soon as it gets produced while the tests run. I found that this then prints the output twice, once when it originally gets produced and then again when the spec has passed. That's because of this line:

https://github.com/onsi/ginkgo/blob/ce3d3731402b67a8d6dd966480924b7133bb5642/reporters/default_reporter.go#L140

Is this intentional?

**Comment by onsi** [comment]
yeah - it's' intentional though admittedly there's not a great reason for doing it.  when you're running in series you'll see `GinkgoWriter` writes emitted in real-time and then again as part of the spec summary.  When you're running in parallel you'll only see it emitted in the summary once.  These slight differences in behavior when running in series/parallel are unfortunate - but the intent is to give you as tight a feedback loop as  as possible when you're trying to debug a spec in real-time.

**Comment by pohly** [comment]
I've arrived at the same conclusion. My solution in PMEM-CSI now is to use -ginkgo.v only when running interactively, with some comments explaining the double output.
